// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const authorizeEmailCharge = `-- name: AuthorizeEmailCharge :one
WITH clock AS MATERIALIZED (
    SELECT now() AS priced_at
),
team_record AS MATERIALIZED (
    SELECT team.id, team.status, team.market_code
    FROM teams AS team
    WHERE team.id = $1
),
market_record AS MATERIALIZED (
    SELECT market.code, market.currency
    FROM billing_markets AS market
    JOIN team_record AS team ON team.market_code = market.code
    WHERE market.is_enabled = true
),
wallet_record AS MATERIALIZED (
    SELECT wallet.team_id, wallet.billing_market, wallet.currency, wallet.balance_units, wallet.tier, wallet.created_at, wallet.updated_at
    FROM team_wallets AS wallet
    WHERE wallet.team_id = $1
    FOR UPDATE
),
existing_authorization AS MATERIALIZED (
    SELECT id, team_id, product, meter, reference_id, usage_allowance_id, sms_rate_id, product_rate_id, billing_market, destination_country, provider, route_type, total_quantity, allowance_quantity, billable_quantity, unit_cost_units, amount_units, currency, tier, priced_at, created_at
    FROM usage_authorizations AS usage_auth
    WHERE usage_auth.team_id = $1
      AND usage_auth.meter = 'email_recipient'
      AND usage_auth.reference_id = $2
),
allowance_record AS MATERIALIZED (
    SELECT allowance.id, allowance.team_id, allowance.meter, allowance.period_start, allowance.period_end, allowance.included_quantity, allowance.consumed_quantity, allowance.created_at, allowance.updated_at
    FROM usage_allowances AS allowance
    CROSS JOIN clock
    WHERE allowance.team_id = $1
      AND allowance.meter = 'email_recipient'
      AND allowance.period_start <= clock.priced_at
      AND allowance.period_end > clock.priced_at
      AND allowance.consumed_quantity < allowance.included_quantity
    ORDER BY allowance.period_start DESC
    LIMIT 1
    FOR UPDATE
),
rate_record AS MATERIALIZED (
    SELECT rate.id, rate.product, rate.meter, rate.billing_market, rate.tier, rate.currency, rate.cost_units, rate.effective_from, rate.effective_until, rate.created_at
    FROM product_rates AS rate
    CROSS JOIN clock
    JOIN wallet_record AS wallet
      ON wallet.billing_market = rate.billing_market
     AND wallet.currency = rate.currency
     AND wallet.tier = rate.tier
    WHERE rate.product = 'email'
      AND rate.meter = 'email_recipient'
      AND rate.effective_from <= clock.priced_at
      AND (rate.effective_until IS NULL OR rate.effective_until > clock.priced_at)
    ORDER BY rate.effective_from DESC
    LIMIT 1
),
plan AS MATERIALIZED (
    SELECT
        wallet.team_id,
        wallet.billing_market,
        wallet.currency,
        wallet.tier,
        wallet.balance_units,
        allowance.id AS usage_allowance_id,
        CASE WHEN allowance.id IS NULL THEN 0::bigint ELSE 1::bigint END AS allowance_quantity,
        rate.id AS product_rate_id,
        COALESCE(rate.cost_units, 0)::bigint AS unit_cost_units,
        clock.priced_at
    FROM wallet_record AS wallet
    CROSS JOIN clock
    LEFT JOIN allowance_record AS allowance ON true
    LEFT JOIN rate_record AS rate ON true
),
priced_plan AS MATERIALIZED (
    SELECT
        plan.team_id, plan.billing_market, plan.currency, plan.tier, plan.balance_units, plan.usage_allowance_id, plan.allowance_quantity, plan.product_rate_id, plan.unit_cost_units, plan.priced_at,
        (1 - plan.allowance_quantity)::bigint AS billable_quantity,
        CASE WHEN plan.allowance_quantity = 1 THEN 0::bigint ELSE plan.unit_cost_units END AS amount_units
    FROM plan
),
inserted_authorization AS (
    INSERT INTO usage_authorizations (
        team_id,
        product,
        meter,
        reference_id,
        usage_allowance_id,
        product_rate_id,
        billing_market,
        total_quantity,
        allowance_quantity,
        billable_quantity,
        unit_cost_units,
        amount_units,
        currency,
        tier,
        priced_at
    )
    SELECT
        plan.team_id,
        'email',
        'email_recipient',
        $2,
        CASE WHEN plan.allowance_quantity > 0 THEN plan.usage_allowance_id END,
        CASE WHEN plan.billable_quantity > 0 THEN plan.product_rate_id END,
        plan.billing_market,
        1,
        plan.allowance_quantity,
        plan.billable_quantity,
        CASE WHEN plan.billable_quantity > 0 THEN plan.unit_cost_units ELSE 0 END,
        plan.amount_units,
        plan.currency,
        plan.tier,
        plan.priced_at
    FROM priced_plan AS plan
    JOIN team_record AS team ON team.id = plan.team_id AND team.status = 'active'
    JOIN market_record AS market ON market.code = plan.billing_market AND market.currency = plan.currency
    WHERE NOT EXISTS (SELECT 1 FROM existing_authorization)
      AND (plan.billable_quantity = 0 OR plan.product_rate_id IS NOT NULL)
      AND plan.balance_units >= plan.amount_units
    ON CONFLICT (team_id, meter, reference_id) DO NOTHING
    RETURNING id, team_id, product, meter, reference_id, usage_allowance_id, sms_rate_id, product_rate_id, billing_market, destination_country, provider, route_type, total_quantity, allowance_quantity, billable_quantity, unit_cost_units, amount_units, currency, tier, priced_at, created_at
),
updated_allowance AS (
    UPDATE usage_allowances AS allowance
    SET consumed_quantity = allowance.consumed_quantity + usage_auth.allowance_quantity,
        updated_at = now()
    FROM inserted_authorization AS usage_auth
    WHERE allowance.id = usage_auth.usage_allowance_id
      AND usage_auth.allowance_quantity > 0
    RETURNING allowance.id, allowance.included_quantity, allowance.consumed_quantity
),
inserted_ledger AS (
    INSERT INTO wallet_ledger (
        team_id,
        usage_authorization_id,
        amount_units,
        transaction_type,
        reference_id
    )
    SELECT
        usage_auth.team_id,
        usage_auth.id,
        -usage_auth.amount_units,
        'usage',
        usage_auth.reference_id
    FROM inserted_authorization AS usage_auth
    WHERE usage_auth.amount_units > 0
    RETURNING team_id, amount_units
),
updated_wallet AS (
    UPDATE team_wallets AS wallet
    SET balance_units = wallet.balance_units + ledger.amount_units,
        updated_at = now()
    FROM inserted_ledger AS ledger
    WHERE wallet.team_id = ledger.team_id
    RETURNING wallet.balance_units
),
resolved_authorization AS MATERIALIZED (
    SELECT id, team_id, product, meter, reference_id, usage_allowance_id, sms_rate_id, product_rate_id, billing_market, destination_country, provider, route_type, total_quantity, allowance_quantity, billable_quantity, unit_cost_units, amount_units, currency, tier, priced_at, created_at FROM existing_authorization
    UNION ALL
    SELECT id, team_id, product, meter, reference_id, usage_allowance_id, sms_rate_id, product_rate_id, billing_market, destination_country, provider, route_type, total_quantity, allowance_quantity, billable_quantity, unit_cost_units, amount_units, currency, tier, priced_at, created_at FROM inserted_authorization
    LIMIT 1
)
SELECT
    CASE
        WHEN NOT EXISTS (SELECT 1 FROM team_record) THEN 'team_not_found'
        WHEN EXISTS (SELECT 1 FROM team_record WHERE status <> 'active') THEN 'team_inactive'
        WHEN NOT EXISTS (SELECT 1 FROM market_record) THEN 'unsupported_market'
        WHEN NOT EXISTS (SELECT 1 FROM wallet_record) THEN 'wallet_not_found'
        WHEN EXISTS (SELECT 1 FROM existing_authorization) THEN 'already_applied'
        WHEN EXISTS (
            SELECT 1 FROM priced_plan
            WHERE billable_quantity > 0 AND product_rate_id IS NULL
        ) THEN 'rate_not_found'
        WHEN EXISTS (
            SELECT 1 FROM priced_plan
            WHERE balance_units < amount_units
        ) THEN 'insufficient_balance'
        WHEN EXISTS (
            SELECT 1 FROM inserted_authorization
            WHERE allowance_quantity = total_quantity
        ) THEN 'allowance_applied'
        WHEN EXISTS (SELECT 1 FROM inserted_authorization) THEN 'applied'
        ELSE 'already_applied'
    END AS outcome,
    COALESCE((SELECT billing_market FROM resolved_authorization), (SELECT billing_market FROM wallet_record), '')::text AS market_code,
    COALESCE((SELECT currency FROM resolved_authorization), (SELECT currency FROM wallet_record), '')::text AS currency,
    COALESCE((SELECT tier FROM resolved_authorization), (SELECT tier FROM wallet_record), '')::text AS tier,
    'email'::text AS product,
    COALESCE((SELECT unit_cost_units FROM resolved_authorization), 0)::bigint AS unit_cost_units,
    1::bigint AS quantity,
    COALESCE((SELECT amount_units FROM resolved_authorization), 0)::bigint AS amount_units,
    COALESCE((SELECT balance_units FROM updated_wallet), (SELECT balance_units FROM wallet_record), 0)::bigint AS balance_units,
    COALESCE((SELECT allowance_quantity > 0 FROM resolved_authorization), false)::boolean AS covered_by_allowance,
    COALESCE(
        (SELECT included_quantity - consumed_quantity FROM updated_allowance),
        (SELECT included_quantity - consumed_quantity FROM allowance_record),
        0
    )::bigint AS remaining_allowance
`

type AuthorizeEmailChargeParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	ReferenceID string    `db:"reference_id" json:"reference_id"`
}

type AuthorizeEmailChargeRow struct {
	Outcome            string `db:"outcome" json:"outcome"`
	MarketCode         string `db:"market_code" json:"market_code"`
	Currency           string `db:"currency" json:"currency"`
	Tier               string `db:"tier" json:"tier"`
	Product            string `db:"product" json:"product"`
	UnitCostUnits      int64  `db:"unit_cost_units" json:"unit_cost_units"`
	Quantity           int64  `db:"quantity" json:"quantity"`
	AmountUnits        int64  `db:"amount_units" json:"amount_units"`
	BalanceUnits       int64  `db:"balance_units" json:"balance_units"`
	CoveredByAllowance bool   `db:"covered_by_allowance" json:"covered_by_allowance"`
	RemainingAllowance int64  `db:"remaining_allowance" json:"remaining_allowance"`
}

func (q *Queries) AuthorizeEmailCharge(ctx context.Context, arg AuthorizeEmailChargeParams) (AuthorizeEmailChargeRow, error) {
	row := q.db.QueryRow(ctx, authorizeEmailCharge, arg.TeamID, arg.ReferenceID)
	var i AuthorizeEmailChargeRow
	err := row.Scan(
		&i.Outcome,
		&i.MarketCode,
		&i.Currency,
		&i.Tier,
		&i.Product,
		&i.UnitCostUnits,
		&i.Quantity,
		&i.AmountUnits,
		&i.BalanceUnits,
		&i.CoveredByAllowance,
		&i.RemainingAllowance,
	)
	return i, err
}

const authorizeSMSCharge = `-- name: AuthorizeSMSCharge :one
WITH clock AS MATERIALIZED (
    SELECT now() AS priced_at
),
team_record AS MATERIALIZED (
    SELECT team.id, team.status, team.market_code
    FROM teams AS team
    WHERE team.id = $2
),
market_record AS MATERIALIZED (
    SELECT market.code, market.currency
    FROM billing_markets AS market
    JOIN team_record AS team ON team.market_code = market.code
    WHERE market.is_enabled = true
),
wallet_record AS MATERIALIZED (
    SELECT wallet.team_id, wallet.billing_market, wallet.currency, wallet.balance_units, wallet.tier, wallet.created_at, wallet.updated_at
    FROM team_wallets AS wallet
    WHERE wallet.team_id = $2
    FOR UPDATE
),
existing_authorization AS MATERIALIZED (
    SELECT id, team_id, product, meter, reference_id, usage_allowance_id, sms_rate_id, product_rate_id, billing_market, destination_country, provider, route_type, total_quantity, allowance_quantity, billable_quantity, unit_cost_units, amount_units, currency, tier, priced_at, created_at
    FROM usage_authorizations AS usage_auth
    WHERE usage_auth.team_id = $2
      AND usage_auth.meter = 'sms_segment'
      AND usage_auth.reference_id = $3
),
allowance_record AS MATERIALIZED (
    SELECT allowance.id, allowance.team_id, allowance.meter, allowance.period_start, allowance.period_end, allowance.included_quantity, allowance.consumed_quantity, allowance.created_at, allowance.updated_at
    FROM usage_allowances AS allowance
    CROSS JOIN clock
    WHERE allowance.team_id = $2
      AND allowance.meter = 'sms_segment'
      AND allowance.period_start <= clock.priced_at
      AND allowance.period_end > clock.priced_at
      AND allowance.consumed_quantity < allowance.included_quantity
    ORDER BY allowance.period_start DESC
    LIMIT 1
    FOR UPDATE
),
rate_record AS MATERIALIZED (
    SELECT rate.id, rate.billing_market, rate.destination_country, rate.provider, rate.route_type, rate.tier, rate.currency, rate.cost_units, rate.effective_from, rate.effective_until, rate.created_at
    FROM sms_rates AS rate
    CROSS JOIN clock
    JOIN wallet_record AS wallet
      ON wallet.billing_market = rate.billing_market
     AND wallet.currency = rate.currency
     AND wallet.tier = rate.tier
    WHERE rate.destination_country = $4
      AND rate.provider = $5
      AND rate.route_type = $6
      AND rate.effective_from <= clock.priced_at
      AND (rate.effective_until IS NULL OR rate.effective_until > clock.priced_at)
    ORDER BY rate.effective_from DESC
    LIMIT 1
),
plan AS MATERIALIZED (
    SELECT
        wallet.team_id,
        wallet.billing_market,
        wallet.currency,
        wallet.tier,
        wallet.balance_units,
        allowance.id AS usage_allowance_id,
        LEAST(
            $1::bigint,
            GREATEST(
                COALESCE(allowance.included_quantity - allowance.consumed_quantity, 0),
                0
            )
        )::bigint AS allowance_quantity,
        rate.id AS sms_rate_id,
        COALESCE(rate.cost_units, 0)::bigint AS unit_cost_units,
        clock.priced_at
    FROM wallet_record AS wallet
    CROSS JOIN clock
    LEFT JOIN allowance_record AS allowance ON true
    LEFT JOIN rate_record AS rate ON true
),
priced_plan AS MATERIALIZED (
    SELECT
        plan.team_id, plan.billing_market, plan.currency, plan.tier, plan.balance_units, plan.usage_allowance_id, plan.allowance_quantity, plan.sms_rate_id, plan.unit_cost_units, plan.priced_at,
        ($1::bigint - plan.allowance_quantity)::bigint AS billable_quantity,
        CASE
            WHEN $1::bigint - plan.allowance_quantity = 0 THEN 0::bigint
            WHEN plan.unit_cost_units > 9223372036854775807 /
                NULLIF($1::bigint - plan.allowance_quantity, 0)
                THEN NULL::bigint
            ELSE plan.unit_cost_units *
                ($1::bigint - plan.allowance_quantity)
        END AS amount_units
    FROM plan
),
inserted_authorization AS (
    INSERT INTO usage_authorizations (
        team_id,
        product,
        meter,
        reference_id,
        usage_allowance_id,
        sms_rate_id,
        billing_market,
        destination_country,
        provider,
        route_type,
        total_quantity,
        allowance_quantity,
        billable_quantity,
        unit_cost_units,
        amount_units,
        currency,
        tier,
        priced_at
    )
    SELECT
        plan.team_id,
        'sms',
        'sms_segment',
        $3,
        CASE WHEN plan.allowance_quantity > 0 THEN plan.usage_allowance_id END,
        CASE WHEN plan.billable_quantity > 0 THEN plan.sms_rate_id END,
        plan.billing_market,
        $4,
        $5,
        $6,
        $1,
        plan.allowance_quantity,
        plan.billable_quantity,
        CASE WHEN plan.billable_quantity > 0 THEN plan.unit_cost_units ELSE 0 END,
        plan.amount_units,
        plan.currency,
        plan.tier,
        plan.priced_at
    FROM priced_plan AS plan
    JOIN team_record AS team ON team.id = plan.team_id AND team.status = 'active'
    JOIN market_record AS market ON market.code = plan.billing_market AND market.currency = plan.currency
    WHERE $1::bigint > 0
      AND NOT EXISTS (SELECT 1 FROM existing_authorization)
      AND plan.amount_units IS NOT NULL
      AND (plan.billable_quantity = 0 OR plan.sms_rate_id IS NOT NULL)
      AND plan.balance_units >= plan.amount_units
    ON CONFLICT (team_id, meter, reference_id) DO NOTHING
    RETURNING id, team_id, product, meter, reference_id, usage_allowance_id, sms_rate_id, product_rate_id, billing_market, destination_country, provider, route_type, total_quantity, allowance_quantity, billable_quantity, unit_cost_units, amount_units, currency, tier, priced_at, created_at
),
updated_allowance AS (
    UPDATE usage_allowances AS allowance
    SET consumed_quantity = allowance.consumed_quantity + usage_auth.allowance_quantity,
        updated_at = now()
    FROM inserted_authorization AS usage_auth
    WHERE allowance.id = usage_auth.usage_allowance_id
      AND usage_auth.allowance_quantity > 0
    RETURNING allowance.id, allowance.included_quantity, allowance.consumed_quantity
),
inserted_ledger AS (
    INSERT INTO wallet_ledger (
        team_id,
        usage_authorization_id,
        amount_units,
        transaction_type,
        reference_id
    )
    SELECT
        usage_auth.team_id,
        usage_auth.id,
        -usage_auth.amount_units,
        'usage',
        usage_auth.reference_id
    FROM inserted_authorization AS usage_auth
    WHERE usage_auth.amount_units > 0
    RETURNING team_id, amount_units
),
updated_wallet AS (
    UPDATE team_wallets AS wallet
    SET balance_units = wallet.balance_units + ledger.amount_units,
        updated_at = now()
    FROM inserted_ledger AS ledger
    WHERE wallet.team_id = ledger.team_id
    RETURNING wallet.balance_units
),
resolved_authorization AS MATERIALIZED (
    SELECT id, team_id, product, meter, reference_id, usage_allowance_id, sms_rate_id, product_rate_id, billing_market, destination_country, provider, route_type, total_quantity, allowance_quantity, billable_quantity, unit_cost_units, amount_units, currency, tier, priced_at, created_at FROM existing_authorization
    UNION ALL
    SELECT id, team_id, product, meter, reference_id, usage_allowance_id, sms_rate_id, product_rate_id, billing_market, destination_country, provider, route_type, total_quantity, allowance_quantity, billable_quantity, unit_cost_units, amount_units, currency, tier, priced_at, created_at FROM inserted_authorization
    LIMIT 1
)
SELECT
    CASE
        WHEN NOT EXISTS (SELECT 1 FROM team_record) THEN 'team_not_found'
        WHEN EXISTS (SELECT 1 FROM team_record WHERE status <> 'active') THEN 'team_inactive'
        WHEN NOT EXISTS (SELECT 1 FROM market_record) THEN 'unsupported_market'
        WHEN NOT EXISTS (SELECT 1 FROM wallet_record) THEN 'wallet_not_found'
        WHEN EXISTS (SELECT 1 FROM existing_authorization) THEN 'already_applied'
        WHEN EXISTS (
            SELECT 1 FROM priced_plan
            WHERE billable_quantity > 0 AND sms_rate_id IS NULL
        ) THEN 'rate_not_found'
        WHEN EXISTS (SELECT 1 FROM priced_plan WHERE amount_units IS NULL) THEN 'amount_overflow'
        WHEN EXISTS (
            SELECT 1 FROM priced_plan
            WHERE amount_units IS NOT NULL AND balance_units < amount_units
        ) THEN 'insufficient_balance'
        WHEN EXISTS (
            SELECT 1 FROM inserted_authorization
            WHERE allowance_quantity = total_quantity
        ) THEN 'allowance_applied'
        WHEN EXISTS (SELECT 1 FROM inserted_authorization) THEN 'applied'
        ELSE 'already_applied'
    END AS outcome,
    COALESCE((SELECT billing_market FROM resolved_authorization), (SELECT billing_market FROM wallet_record), '')::text AS market_code,
    COALESCE((SELECT currency FROM resolved_authorization), (SELECT currency FROM wallet_record), '')::text AS currency,
    COALESCE((SELECT tier FROM resolved_authorization), (SELECT tier FROM wallet_record), '')::text AS tier,
    'sms'::text AS product,
    COALESCE((SELECT unit_cost_units FROM resolved_authorization), 0)::bigint AS unit_cost_units,
    $1::bigint AS quantity,
    COALESCE((SELECT amount_units FROM resolved_authorization), 0)::bigint AS amount_units,
    COALESCE((SELECT balance_units FROM updated_wallet), (SELECT balance_units FROM wallet_record), 0)::bigint AS balance_units,
    COALESCE((SELECT allowance_quantity > 0 FROM resolved_authorization), false)::boolean AS covered_by_allowance,
    COALESCE(
        (SELECT included_quantity - consumed_quantity FROM updated_allowance),
        (SELECT included_quantity - consumed_quantity FROM allowance_record),
        0
    )::bigint AS remaining_allowance
`

type AuthorizeSMSChargeParams struct {
	Quantity           int64     `db:"quantity" json:"quantity"`
	TeamID             uuid.UUID `db:"team_id" json:"team_id"`
	ReferenceID        string    `db:"reference_id" json:"reference_id"`
	DestinationCountry string    `db:"destination_country" json:"destination_country"`
	Provider           string    `db:"provider" json:"provider"`
	RouteType          string    `db:"route_type" json:"route_type"`
}

type AuthorizeSMSChargeRow struct {
	Outcome            string `db:"outcome" json:"outcome"`
	MarketCode         string `db:"market_code" json:"market_code"`
	Currency           string `db:"currency" json:"currency"`
	Tier               string `db:"tier" json:"tier"`
	Product            string `db:"product" json:"product"`
	UnitCostUnits      int64  `db:"unit_cost_units" json:"unit_cost_units"`
	Quantity           int64  `db:"quantity" json:"quantity"`
	AmountUnits        int64  `db:"amount_units" json:"amount_units"`
	BalanceUnits       int64  `db:"balance_units" json:"balance_units"`
	CoveredByAllowance bool   `db:"covered_by_allowance" json:"covered_by_allowance"`
	RemainingAllowance int64  `db:"remaining_allowance" json:"remaining_allowance"`
}

func (q *Queries) AuthorizeSMSCharge(ctx context.Context, arg AuthorizeSMSChargeParams) (AuthorizeSMSChargeRow, error) {
	row := q.db.QueryRow(ctx, authorizeSMSCharge,
		arg.Quantity,
		arg.TeamID,
		arg.ReferenceID,
		arg.DestinationCountry,
		arg.Provider,
		arg.RouteType,
	)
	var i AuthorizeSMSChargeRow
	err := row.Scan(
		&i.Outcome,
		&i.MarketCode,
		&i.Currency,
		&i.Tier,
		&i.Product,
		&i.UnitCostUnits,
		&i.Quantity,
		&i.AmountUnits,
		&i.BalanceUnits,
		&i.CoveredByAllowance,
		&i.RemainingAllowance,
	)
	return i, err
}

const creditTeamWallet = `-- name: CreditTeamWallet :one
WITH locked_wallet AS MATERIALIZED (
    SELECT wallet.team_id, wallet.billing_market, wallet.currency, wallet.balance_units, wallet.tier, wallet.created_at, wallet.updated_at
    FROM team_wallets AS wallet
    WHERE wallet.team_id = $1
    FOR UPDATE
),
inserted_ledger AS (
    INSERT INTO wallet_ledger (
        team_id,
        amount_units,
        transaction_type,
        reference_id
    )
    SELECT
        wallet.team_id,
        $2,
        $3,
        $4
    FROM locked_wallet AS wallet
    WHERE $2::bigint > 0
      AND $3::text <> 'usage'
    ON CONFLICT (team_id, transaction_type, reference_id) DO NOTHING
    RETURNING team_id, amount_units
),
updated_wallet AS (
    UPDATE team_wallets AS wallet
    SET balance_units = wallet.balance_units + ledger.amount_units,
        updated_at = now()
    FROM inserted_ledger AS ledger
    WHERE wallet.team_id = ledger.team_id
    RETURNING wallet.team_id, wallet.billing_market, wallet.currency, wallet.balance_units, wallet.tier, wallet.created_at, wallet.updated_at
)
SELECT team_id, billing_market, currency, balance_units, tier, created_at, updated_at
FROM updated_wallet
`

type CreditTeamWalletParams struct {
	TeamID          uuid.UUID `db:"team_id" json:"team_id"`
	AmountUnits     int64     `db:"amount_units" json:"amount_units"`
	TransactionType string    `db:"transaction_type" json:"transaction_type"`
	ReferenceID     string    `db:"reference_id" json:"reference_id"`
}

type CreditTeamWalletRow struct {
	TeamID        uuid.UUID          `db:"team_id" json:"team_id"`
	BillingMarket string             `db:"billing_market" json:"billing_market"`
	Currency      string             `db:"currency" json:"currency"`
	BalanceUnits  int64              `db:"balance_units" json:"balance_units"`
	Tier          string             `db:"tier" json:"tier"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreditTeamWallet(ctx context.Context, arg CreditTeamWalletParams) (CreditTeamWalletRow, error) {
	row := q.db.QueryRow(ctx, creditTeamWallet,
		arg.TeamID,
		arg.AmountUnits,
		arg.TransactionType,
		arg.ReferenceID,
	)
	var i CreditTeamWalletRow
	err := row.Scan(
		&i.TeamID,
		&i.BillingMarket,
		&i.Currency,
		&i.BalanceUnits,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const debitTeamWallet = `-- name: DebitTeamWallet :one
WITH locked_wallet AS MATERIALIZED (
    SELECT wallet.team_id, wallet.billing_market, wallet.currency, wallet.balance_units, wallet.tier, wallet.created_at, wallet.updated_at
    FROM team_wallets AS wallet
    WHERE wallet.team_id = $1
    FOR UPDATE
),
inserted_ledger AS (
    INSERT INTO wallet_ledger (
        team_id,
        amount_units,
        transaction_type,
        reference_id
    )
    SELECT
        wallet.team_id,
        -$2::bigint,
        $3,
        $4
    FROM locked_wallet AS wallet
    WHERE $2::bigint > 0
      AND $3::text <> 'usage'
      AND wallet.balance_units >= $2
    ON CONFLICT (team_id, transaction_type, reference_id) DO NOTHING
    RETURNING team_id, amount_units
),
updated_wallet AS (
    UPDATE team_wallets AS wallet
    SET balance_units = wallet.balance_units + ledger.amount_units,
        updated_at = now()
    FROM inserted_ledger AS ledger
    WHERE wallet.team_id = ledger.team_id
    RETURNING wallet.team_id, wallet.billing_market, wallet.currency, wallet.balance_units, wallet.tier, wallet.created_at, wallet.updated_at
)
SELECT team_id, billing_market, currency, balance_units, tier, created_at, updated_at
FROM updated_wallet
`

type DebitTeamWalletParams struct {
	TeamID          uuid.UUID `db:"team_id" json:"team_id"`
	AmountUnits     int64     `db:"amount_units" json:"amount_units"`
	TransactionType string    `db:"transaction_type" json:"transaction_type"`
	ReferenceID     string    `db:"reference_id" json:"reference_id"`
}

type DebitTeamWalletRow struct {
	TeamID        uuid.UUID          `db:"team_id" json:"team_id"`
	BillingMarket string             `db:"billing_market" json:"billing_market"`
	Currency      string             `db:"currency" json:"currency"`
	BalanceUnits  int64              `db:"balance_units" json:"balance_units"`
	Tier          string             `db:"tier" json:"tier"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) DebitTeamWallet(ctx context.Context, arg DebitTeamWalletParams) (DebitTeamWalletRow, error) {
	row := q.db.QueryRow(ctx, debitTeamWallet,
		arg.TeamID,
		arg.AmountUnits,
		arg.TransactionType,
		arg.ReferenceID,
	)
	var i DebitTeamWalletRow
	err := row.Scan(
		&i.TeamID,
		&i.BillingMarket,
		&i.Currency,
		&i.BalanceUnits,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveProductRate = `-- name: GetActiveProductRate :one
SELECT id, product, meter, billing_market, tier, currency, cost_units, effective_from, effective_until, created_at
FROM product_rates
WHERE product = $1
  AND meter = $2
  AND billing_market = $3
  AND tier = $4
  AND effective_from <= $5
  AND (effective_until IS NULL OR effective_until > $5)
ORDER BY effective_from DESC
LIMIT 1
`

type GetActiveProductRateParams struct {
	Product       string             `db:"product" json:"product"`
	Meter         string             `db:"meter" json:"meter"`
	BillingMarket string             `db:"billing_market" json:"billing_market"`
	Tier          string             `db:"tier" json:"tier"`
	PricedAt      pgtype.Timestamptz `db:"priced_at" json:"priced_at"`
}

func (q *Queries) GetActiveProductRate(ctx context.Context, arg GetActiveProductRateParams) (ProductRate, error) {
	row := q.db.QueryRow(ctx, getActiveProductRate,
		arg.Product,
		arg.Meter,
		arg.BillingMarket,
		arg.Tier,
		arg.PricedAt,
	)
	var i ProductRate
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.Meter,
		&i.BillingMarket,
		&i.Tier,
		&i.Currency,
		&i.CostUnits,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamWallet = `-- name: GetTeamWallet :one
SELECT team_id, billing_market, currency, balance_units, tier, created_at, updated_at
FROM team_wallets
WHERE team_id = $1
`

type GetTeamWalletParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetTeamWallet(ctx context.Context, arg GetTeamWalletParams) (TeamWallet, error) {
	row := q.db.QueryRow(ctx, getTeamWallet, arg.TeamID)
	var i TeamWallet
	err := row.Scan(
		&i.TeamID,
		&i.BillingMarket,
		&i.Currency,
		&i.BalanceUnits,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWalletLedger = `-- name: ListWalletLedger :many
SELECT id, team_id, usage_authorization_id, amount_units, transaction_type, reference_id, created_at
FROM wallet_ledger
WHERE team_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListWalletLedgerParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListWalletLedger(ctx context.Context, arg ListWalletLedgerParams) ([]WalletLedger, error) {
	rows, err := q.db.Query(ctx, listWalletLedger, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletLedger{}
	for rows.Next() {
		var i WalletLedger
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UsageAuthorizationID,
			&i.AmountUnits,
			&i.TransactionType,
			&i.ReferenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeamWalletTier = `-- name: UpdateTeamWalletTier :one
UPDATE team_wallets
SET tier = $1,
    updated_at = now()
WHERE team_id = $2
RETURNING team_id, billing_market, currency, balance_units, tier, created_at, updated_at
`

type UpdateTeamWalletTierParams struct {
	Tier   string    `db:"tier" json:"tier"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateTeamWalletTier(ctx context.Context, arg UpdateTeamWalletTierParams) (TeamWallet, error) {
	row := q.db.QueryRow(ctx, updateTeamWalletTier, arg.Tier, arg.TeamID)
	var i TeamWallet
	err := row.Scan(
		&i.TeamID,
		&i.BillingMarket,
		&i.Currency,
		&i.BalanceUnits,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
