// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: broadcast_recipients.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBroadcastRecipient = `-- name: CreateBroadcastRecipient :one
INSERT INTO broadcast_recipients (
    team_id, broadcast_id, contact_id, email, normalized_email,
    first_name, last_name, contact_snapshot, status, exclusion_reason
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10
)
RETURNING id, team_id, broadcast_id, contact_id, email, normalized_email, first_name, last_name, contact_snapshot, status, exclusion_reason, email_message_id, created_at, queued_at
`

type CreateBroadcastRecipientParams struct {
	TeamID          uuid.UUID  `db:"team_id" json:"team_id"`
	BroadcastID     uuid.UUID  `db:"broadcast_id" json:"broadcast_id"`
	ContactID       *uuid.UUID `db:"contact_id" json:"contact_id"`
	Email           string     `db:"email" json:"email"`
	NormalizedEmail string     `db:"normalized_email" json:"normalized_email"`
	FirstName       *string    `db:"first_name" json:"first_name"`
	LastName        *string    `db:"last_name" json:"last_name"`
	ContactSnapshot []byte     `db:"contact_snapshot" json:"contact_snapshot"`
	Status          string     `db:"status" json:"status"`
	ExclusionReason *string    `db:"exclusion_reason" json:"exclusion_reason"`
}

func (q *Queries) CreateBroadcastRecipient(ctx context.Context, arg CreateBroadcastRecipientParams) (BroadcastRecipient, error) {
	row := q.db.QueryRow(ctx, createBroadcastRecipient,
		arg.TeamID,
		arg.BroadcastID,
		arg.ContactID,
		arg.Email,
		arg.NormalizedEmail,
		arg.FirstName,
		arg.LastName,
		arg.ContactSnapshot,
		arg.Status,
		arg.ExclusionReason,
	)
	var i BroadcastRecipient
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BroadcastID,
		&i.ContactID,
		&i.Email,
		&i.NormalizedEmail,
		&i.FirstName,
		&i.LastName,
		&i.ContactSnapshot,
		&i.Status,
		&i.ExclusionReason,
		&i.EmailMessageID,
		&i.CreatedAt,
		&i.QueuedAt,
	)
	return i, err
}

const listBroadcastRecipients = `-- name: ListBroadcastRecipients :many
SELECT id, team_id, broadcast_id, contact_id, email, normalized_email, first_name, last_name, contact_snapshot, status, exclusion_reason, email_message_id, created_at, queued_at
FROM broadcast_recipients
WHERE team_id = $1
  AND broadcast_id = $2
ORDER BY created_at ASC, id ASC
LIMIT $4
OFFSET $3
`

type ListBroadcastRecipientsParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	BroadcastID uuid.UUID `db:"broadcast_id" json:"broadcast_id"`
	PageOffset  int32     `db:"page_offset" json:"page_offset"`
	PageLimit   int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListBroadcastRecipients(ctx context.Context, arg ListBroadcastRecipientsParams) ([]BroadcastRecipient, error) {
	rows, err := q.db.Query(ctx, listBroadcastRecipients,
		arg.TeamID,
		arg.BroadcastID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BroadcastRecipient{}
	for rows.Next() {
		var i BroadcastRecipient
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.BroadcastID,
			&i.ContactID,
			&i.Email,
			&i.NormalizedEmail,
			&i.FirstName,
			&i.LastName,
			&i.ContactSnapshot,
			&i.Status,
			&i.ExclusionReason,
			&i.EmailMessageID,
			&i.CreatedAt,
			&i.QueuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBroadcastRecipientQueued = `-- name: SetBroadcastRecipientQueued :one
UPDATE broadcast_recipients
SET status = 'queued', email_message_id = $1, queued_at = now()
WHERE id = $2
  AND team_id = $3
  AND broadcast_id = $4
  AND status = 'pending'
RETURNING id, team_id, broadcast_id, contact_id, email, normalized_email, first_name, last_name, contact_snapshot, status, exclusion_reason, email_message_id, created_at, queued_at
`

type SetBroadcastRecipientQueuedParams struct {
	EmailMessageID *uuid.UUID `db:"email_message_id" json:"email_message_id"`
	ID             uuid.UUID  `db:"id" json:"id"`
	TeamID         uuid.UUID  `db:"team_id" json:"team_id"`
	BroadcastID    uuid.UUID  `db:"broadcast_id" json:"broadcast_id"`
}

func (q *Queries) SetBroadcastRecipientQueued(ctx context.Context, arg SetBroadcastRecipientQueuedParams) (BroadcastRecipient, error) {
	row := q.db.QueryRow(ctx, setBroadcastRecipientQueued,
		arg.EmailMessageID,
		arg.ID,
		arg.TeamID,
		arg.BroadcastID,
	)
	var i BroadcastRecipient
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BroadcastID,
		&i.ContactID,
		&i.Email,
		&i.NormalizedEmail,
		&i.FirstName,
		&i.LastName,
		&i.ContactSnapshot,
		&i.Status,
		&i.ExclusionReason,
		&i.EmailMessageID,
		&i.CreatedAt,
		&i.QueuedAt,
	)
	return i, err
}
