// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: broadcasts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelScheduledBroadcast = `-- name: CancelScheduledBroadcast :one
UPDATE broadcasts
SET status = 'draft',
    template_version_id = NULL,
    scheduled_at = NULL,
    canceled_at = now(),
    revision = revision + 1,
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status = 'scheduled'
  AND deleted_at IS NULL
RETURNING id, team_id, name, status, segment_id, topic_id, template_id, template_version_id, variable_bindings, scheduled_at, queued_at, sent_at, canceled_at, audience_count, eligible_count, suppressed_count, queued_count, failed_count, revision, created_at, updated_at, deleted_at
`

type CancelScheduledBroadcastParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) CancelScheduledBroadcast(ctx context.Context, arg CancelScheduledBroadcastParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, cancelScheduledBroadcast, arg.ID, arg.TeamID)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.TopicID,
		&i.TemplateID,
		&i.TemplateVersionID,
		&i.VariableBindings,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.SentAt,
		&i.CanceledAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.SuppressedCount,
		&i.QueuedCount,
		&i.FailedCount,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createBroadcast = `-- name: CreateBroadcast :one
INSERT INTO broadcasts (
    team_id, name, segment_id, topic_id, template_id, variable_bindings
) VALUES (
    $1, $2, $3, $4,
    $5, $6
)
RETURNING id, team_id, name, status, segment_id, topic_id, template_id, template_version_id, variable_bindings, scheduled_at, queued_at, sent_at, canceled_at, audience_count, eligible_count, suppressed_count, queued_count, failed_count, revision, created_at, updated_at, deleted_at
`

type CreateBroadcastParams struct {
	TeamID           uuid.UUID  `db:"team_id" json:"team_id"`
	Name             string     `db:"name" json:"name"`
	SegmentID        uuid.UUID  `db:"segment_id" json:"segment_id"`
	TopicID          *uuid.UUID `db:"topic_id" json:"topic_id"`
	TemplateID       uuid.UUID  `db:"template_id" json:"template_id"`
	VariableBindings []byte     `db:"variable_bindings" json:"variable_bindings"`
}

func (q *Queries) CreateBroadcast(ctx context.Context, arg CreateBroadcastParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, createBroadcast,
		arg.TeamID,
		arg.Name,
		arg.SegmentID,
		arg.TopicID,
		arg.TemplateID,
		arg.VariableBindings,
	)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.TopicID,
		&i.TemplateID,
		&i.TemplateVersionID,
		&i.VariableBindings,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.SentAt,
		&i.CanceledAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.SuppressedCount,
		&i.QueuedCount,
		&i.FailedCount,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const duplicateBroadcast = `-- name: DuplicateBroadcast :one
INSERT INTO broadcasts (
    team_id, name, segment_id, topic_id, template_id, variable_bindings
)
SELECT
    source.team_id,
    $1,
    source.segment_id,
    source.topic_id,
    source.template_id,
    source.variable_bindings
FROM broadcasts AS source
WHERE source.id = $2
  AND source.team_id = $3
  AND source.deleted_at IS NULL
RETURNING id, team_id, name, status, segment_id, topic_id, template_id, template_version_id, variable_bindings, scheduled_at, queued_at, sent_at, canceled_at, audience_count, eligible_count, suppressed_count, queued_count, failed_count, revision, created_at, updated_at, deleted_at
`

type DuplicateBroadcastParams struct {
	Name     string    `db:"name" json:"name"`
	SourceID uuid.UUID `db:"source_id" json:"source_id"`
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DuplicateBroadcast(ctx context.Context, arg DuplicateBroadcastParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, duplicateBroadcast, arg.Name, arg.SourceID, arg.TeamID)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.TopicID,
		&i.TemplateID,
		&i.TemplateVersionID,
		&i.VariableBindings,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.SentAt,
		&i.CanceledAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.SuppressedCount,
		&i.QueuedCount,
		&i.FailedCount,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBroadcast = `-- name: GetBroadcast :one
SELECT id, team_id, name, status, segment_id, topic_id, template_id, template_version_id, variable_bindings, scheduled_at, queued_at, sent_at, canceled_at, audience_count, eligible_count, suppressed_count, queued_count, failed_count, revision, created_at, updated_at, deleted_at
FROM broadcasts
WHERE id = $1
  AND team_id = $2
  AND deleted_at IS NULL
`

type GetBroadcastParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetBroadcast(ctx context.Context, arg GetBroadcastParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, getBroadcast, arg.ID, arg.TeamID)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.TopicID,
		&i.TemplateID,
		&i.TemplateVersionID,
		&i.VariableBindings,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.SentAt,
		&i.CanceledAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.SuppressedCount,
		&i.QueuedCount,
		&i.FailedCount,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBroadcasts = `-- name: ListBroadcasts :many
SELECT id, team_id, name, status, segment_id, topic_id, template_id, template_version_id, variable_bindings, scheduled_at, queued_at, sent_at, canceled_at, audience_count, eligible_count, suppressed_count, queued_count, failed_count, revision, created_at, updated_at, deleted_at
FROM broadcasts
WHERE team_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListBroadcastsParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListBroadcasts(ctx context.Context, arg ListBroadcastsParams) ([]Broadcast, error) {
	rows, err := q.db.Query(ctx, listBroadcasts, arg.TeamID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcast{}
	for rows.Next() {
		var i Broadcast
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Status,
			&i.SegmentID,
			&i.TopicID,
			&i.TemplateID,
			&i.TemplateVersionID,
			&i.VariableBindings,
			&i.ScheduledAt,
			&i.QueuedAt,
			&i.SentAt,
			&i.CanceledAt,
			&i.AudienceCount,
			&i.EligibleCount,
			&i.SuppressedCount,
			&i.QueuedCount,
			&i.FailedCount,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueBroadcast = `-- name: QueueBroadcast :one
UPDATE broadcasts
SET status = 'queued',
    template_version_id = $1,
    scheduled_at = NULL,
    queued_at = now(),
    canceled_at = NULL,
    revision = revision + 1,
    updated_at = now()
WHERE id = $2
  AND team_id = $3
  AND status = 'draft'
  AND deleted_at IS NULL
RETURNING id, team_id, name, status, segment_id, topic_id, template_id, template_version_id, variable_bindings, scheduled_at, queued_at, sent_at, canceled_at, audience_count, eligible_count, suppressed_count, queued_count, failed_count, revision, created_at, updated_at, deleted_at
`

type QueueBroadcastParams struct {
	TemplateVersionID *uuid.UUID `db:"template_version_id" json:"template_version_id"`
	ID                uuid.UUID  `db:"id" json:"id"`
	TeamID            uuid.UUID  `db:"team_id" json:"team_id"`
}

func (q *Queries) QueueBroadcast(ctx context.Context, arg QueueBroadcastParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, queueBroadcast, arg.TemplateVersionID, arg.ID, arg.TeamID)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.TopicID,
		&i.TemplateID,
		&i.TemplateVersionID,
		&i.VariableBindings,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.SentAt,
		&i.CanceledAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.SuppressedCount,
		&i.QueuedCount,
		&i.FailedCount,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const scheduleBroadcast = `-- name: ScheduleBroadcast :one
UPDATE broadcasts
SET status = 'scheduled',
    template_version_id = $1,
    scheduled_at = $2,
    canceled_at = NULL,
    revision = revision + 1,
    updated_at = now()
WHERE id = $3
  AND team_id = $4
  AND status = 'draft'
  AND deleted_at IS NULL
RETURNING id, team_id, name, status, segment_id, topic_id, template_id, template_version_id, variable_bindings, scheduled_at, queued_at, sent_at, canceled_at, audience_count, eligible_count, suppressed_count, queued_count, failed_count, revision, created_at, updated_at, deleted_at
`

type ScheduleBroadcastParams struct {
	TemplateVersionID *uuid.UUID         `db:"template_version_id" json:"template_version_id"`
	ScheduledAt       pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	ID                uuid.UUID          `db:"id" json:"id"`
	TeamID            uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) ScheduleBroadcast(ctx context.Context, arg ScheduleBroadcastParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, scheduleBroadcast,
		arg.TemplateVersionID,
		arg.ScheduledAt,
		arg.ID,
		arg.TeamID,
	)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.TopicID,
		&i.TemplateID,
		&i.TemplateVersionID,
		&i.VariableBindings,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.SentAt,
		&i.CanceledAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.SuppressedCount,
		&i.QueuedCount,
		&i.FailedCount,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteBroadcast = `-- name: SoftDeleteBroadcast :one
UPDATE broadcasts
SET deleted_at = now(), updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status IN ('draft','canceled')
  AND deleted_at IS NULL
RETURNING id, team_id, name, status, segment_id, topic_id, template_id, template_version_id, variable_bindings, scheduled_at, queued_at, sent_at, canceled_at, audience_count, eligible_count, suppressed_count, queued_count, failed_count, revision, created_at, updated_at, deleted_at
`

type SoftDeleteBroadcastParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) SoftDeleteBroadcast(ctx context.Context, arg SoftDeleteBroadcastParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, softDeleteBroadcast, arg.ID, arg.TeamID)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.TopicID,
		&i.TemplateID,
		&i.TemplateVersionID,
		&i.VariableBindings,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.SentAt,
		&i.CanceledAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.SuppressedCount,
		&i.QueuedCount,
		&i.FailedCount,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateBroadcastDraft = `-- name: UpdateBroadcastDraft :one
UPDATE broadcasts
SET name = $1,
    segment_id = $2,
    topic_id = $3,
    template_id = $4,
    variable_bindings = $5,
    revision = revision + 1,
    updated_at = now()
WHERE id = $6
  AND team_id = $7
  AND status = 'draft'
  AND revision = $8
  AND deleted_at IS NULL
RETURNING id, team_id, name, status, segment_id, topic_id, template_id, template_version_id, variable_bindings, scheduled_at, queued_at, sent_at, canceled_at, audience_count, eligible_count, suppressed_count, queued_count, failed_count, revision, created_at, updated_at, deleted_at
`

type UpdateBroadcastDraftParams struct {
	Name             string     `db:"name" json:"name"`
	SegmentID        uuid.UUID  `db:"segment_id" json:"segment_id"`
	TopicID          *uuid.UUID `db:"topic_id" json:"topic_id"`
	TemplateID       uuid.UUID  `db:"template_id" json:"template_id"`
	VariableBindings []byte     `db:"variable_bindings" json:"variable_bindings"`
	ID               uuid.UUID  `db:"id" json:"id"`
	TeamID           uuid.UUID  `db:"team_id" json:"team_id"`
	Revision         int64      `db:"revision" json:"revision"`
}

func (q *Queries) UpdateBroadcastDraft(ctx context.Context, arg UpdateBroadcastDraftParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, updateBroadcastDraft,
		arg.Name,
		arg.SegmentID,
		arg.TopicID,
		arg.TemplateID,
		arg.VariableBindings,
		arg.ID,
		arg.TeamID,
		arg.Revision,
	)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.TopicID,
		&i.TemplateID,
		&i.TemplateVersionID,
		&i.VariableBindings,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.SentAt,
		&i.CanceledAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.SuppressedCount,
		&i.QueuedCount,
		&i.FailedCount,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
