// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact_topics.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const contactTopicCursorExists = `-- name: ContactTopicCursorExists :one
SELECT EXISTS (
    SELECT 1
    FROM topics
    WHERE id = $1
      AND team_id = $2
)
`

type ContactTopicCursorExistsParams struct {
	CursorID uuid.UUID `db:"cursor_id" json:"cursor_id"`
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ContactTopicCursorExists(ctx context.Context, arg ContactTopicCursorExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, contactTopicCursorExists, arg.CursorID, arg.TeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listContactTopics = `-- name: ListContactTopics :many
SELECT
    topic.id,
    topic.name,
    topic.description,
    COALESCE(subscription.subscription, topic.default_subscription) AS subscription
FROM topics AS topic
LEFT JOIN contact_topic_subscriptions AS subscription
  ON subscription.team_id = topic.team_id
 AND subscription.topic_id = topic.id
 AND subscription.contact_id = $1
WHERE topic.team_id = $2
ORDER BY topic.created_at DESC, topic.id DESC
LIMIT $3
`

type ListContactTopicsParams struct {
	ScopeContactID uuid.UUID `db:"scope_contact_id" json:"scope_contact_id"`
	ScopeTeamID    uuid.UUID `db:"scope_team_id" json:"scope_team_id"`
	PageLimit      int32     `db:"page_limit" json:"page_limit"`
}

type ListContactTopicsRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	Description  *string   `db:"description" json:"description"`
	Subscription string    `db:"subscription" json:"subscription"`
}

func (q *Queries) ListContactTopics(ctx context.Context, arg ListContactTopicsParams) ([]ListContactTopicsRow, error) {
	rows, err := q.db.Query(ctx, listContactTopics, arg.ScopeContactID, arg.ScopeTeamID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactTopicsRow{}
	for rows.Next() {
		var i ListContactTopicsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Subscription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactTopicsAfter = `-- name: ListContactTopicsAfter :many
SELECT
    topic.id,
    topic.name,
    topic.description,
    COALESCE(subscription.subscription, topic.default_subscription) AS subscription
FROM topics AS topic
LEFT JOIN contact_topic_subscriptions AS subscription
  ON subscription.team_id = topic.team_id
 AND subscription.topic_id = topic.id
 AND subscription.contact_id = $1
WHERE topic.team_id = $2
  AND (topic.created_at, topic.id) < (
      SELECT cursor_topic.created_at, cursor_topic.id
      FROM topics AS cursor_topic
      WHERE cursor_topic.id = $3
        AND cursor_topic.team_id = $2
  )
ORDER BY topic.created_at DESC, topic.id DESC
LIMIT $4
`

type ListContactTopicsAfterParams struct {
	ScopeContactID uuid.UUID `db:"scope_contact_id" json:"scope_contact_id"`
	ScopeTeamID    uuid.UUID `db:"scope_team_id" json:"scope_team_id"`
	CursorID       uuid.UUID `db:"cursor_id" json:"cursor_id"`
	PageLimit      int32     `db:"page_limit" json:"page_limit"`
}

type ListContactTopicsAfterRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	Description  *string   `db:"description" json:"description"`
	Subscription string    `db:"subscription" json:"subscription"`
}

func (q *Queries) ListContactTopicsAfter(ctx context.Context, arg ListContactTopicsAfterParams) ([]ListContactTopicsAfterRow, error) {
	rows, err := q.db.Query(ctx, listContactTopicsAfter,
		arg.ScopeContactID,
		arg.ScopeTeamID,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactTopicsAfterRow{}
	for rows.Next() {
		var i ListContactTopicsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Subscription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactTopicsBefore = `-- name: ListContactTopicsBefore :many
SELECT
    topic.id,
    topic.name,
    topic.description,
    COALESCE(subscription.subscription, topic.default_subscription) AS subscription
FROM topics AS topic
LEFT JOIN contact_topic_subscriptions AS subscription
  ON subscription.team_id = topic.team_id
 AND subscription.topic_id = topic.id
 AND subscription.contact_id = $1
WHERE topic.team_id = $2
  AND (topic.created_at, topic.id) > (
      SELECT cursor_topic.created_at, cursor_topic.id
      FROM topics AS cursor_topic
      WHERE cursor_topic.id = $3
        AND cursor_topic.team_id = $2
  )
ORDER BY topic.created_at ASC, topic.id ASC
LIMIT $4
`

type ListContactTopicsBeforeParams struct {
	ScopeContactID uuid.UUID `db:"scope_contact_id" json:"scope_contact_id"`
	ScopeTeamID    uuid.UUID `db:"scope_team_id" json:"scope_team_id"`
	CursorID       uuid.UUID `db:"cursor_id" json:"cursor_id"`
	PageLimit      int32     `db:"page_limit" json:"page_limit"`
}

type ListContactTopicsBeforeRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	Description  *string   `db:"description" json:"description"`
	Subscription string    `db:"subscription" json:"subscription"`
}

func (q *Queries) ListContactTopicsBefore(ctx context.Context, arg ListContactTopicsBeforeParams) ([]ListContactTopicsBeforeRow, error) {
	rows, err := q.db.Query(ctx, listContactTopicsBefore,
		arg.ScopeContactID,
		arg.ScopeTeamID,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactTopicsBeforeRow{}
	for rows.Next() {
		var i ListContactTopicsBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Subscription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContactTopicSubscription = `-- name: UpsertContactTopicSubscription :one
INSERT INTO contact_topic_subscriptions (
    team_id,
    contact_id,
    topic_id,
    subscription
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (contact_id, topic_id)
DO UPDATE SET
    subscription = EXCLUDED.subscription,
    updated_at = now()
RETURNING topic_id
`

type UpsertContactTopicSubscriptionParams struct {
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
	ContactID    uuid.UUID `db:"contact_id" json:"contact_id"`
	TopicID      uuid.UUID `db:"topic_id" json:"topic_id"`
	Subscription string    `db:"subscription" json:"subscription"`
}

func (q *Queries) UpsertContactTopicSubscription(ctx context.Context, arg UpsertContactTopicSubscriptionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertContactTopicSubscription,
		arg.TeamID,
		arg.ContactID,
		arg.TopicID,
		arg.Subscription,
	)
	var topic_id uuid.UUID
	err := row.Scan(&topic_id)
	return topic_id, err
}
