// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact_properties.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContactProperty = `-- name: CreateContactProperty :one
INSERT INTO contact_properties (
    team_id,
    key,
    value_type,
    fallback_string,
    fallback_number
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, team_id, key, value_type, fallback_string, fallback_number, created_at, updated_at
`

type CreateContactPropertyParams struct {
	TeamID         uuid.UUID      `db:"team_id" json:"team_id"`
	Key            string         `db:"key" json:"key"`
	ValueType      string         `db:"value_type" json:"value_type"`
	FallbackString *string        `db:"fallback_string" json:"fallback_string"`
	FallbackNumber pgtype.Numeric `db:"fallback_number" json:"fallback_number"`
}

func (q *Queries) CreateContactProperty(ctx context.Context, arg CreateContactPropertyParams) (ContactProperty, error) {
	row := q.db.QueryRow(ctx, createContactProperty,
		arg.TeamID,
		arg.Key,
		arg.ValueType,
		arg.FallbackString,
		arg.FallbackNumber,
	)
	var i ContactProperty
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.ValueType,
		&i.FallbackString,
		&i.FallbackNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContactProperty = `-- name: DeleteContactProperty :one
DELETE FROM contact_properties
WHERE id = $1
  AND team_id = $2
RETURNING id, team_id, key, value_type, fallback_string, fallback_number, created_at, updated_at
`

type DeleteContactPropertyParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteContactProperty(ctx context.Context, arg DeleteContactPropertyParams) (ContactProperty, error) {
	row := q.db.QueryRow(ctx, deleteContactProperty, arg.ID, arg.TeamID)
	var i ContactProperty
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.ValueType,
		&i.FallbackString,
		&i.FallbackNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactProperty = `-- name: GetContactProperty :one
SELECT id, team_id, key, value_type, fallback_string, fallback_number, created_at, updated_at
FROM contact_properties
WHERE id = $1
  AND team_id = $2
`

type GetContactPropertyParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetContactProperty(ctx context.Context, arg GetContactPropertyParams) (ContactProperty, error) {
	row := q.db.QueryRow(ctx, getContactProperty, arg.ID, arg.TeamID)
	var i ContactProperty
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.ValueType,
		&i.FallbackString,
		&i.FallbackNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactPropertyByKey = `-- name: GetContactPropertyByKey :one
SELECT id, team_id, key, value_type, fallback_string, fallback_number, created_at, updated_at
FROM contact_properties
WHERE key = $1
  AND team_id = $2
`

type GetContactPropertyByKeyParams struct {
	Key    string    `db:"key" json:"key"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetContactPropertyByKey(ctx context.Context, arg GetContactPropertyByKeyParams) (ContactProperty, error) {
	row := q.db.QueryRow(ctx, getContactPropertyByKey, arg.Key, arg.TeamID)
	var i ContactProperty
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.ValueType,
		&i.FallbackString,
		&i.FallbackNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContactProperties = `-- name: ListContactProperties :many
SELECT id, team_id, key, value_type, fallback_string, fallback_number, created_at, updated_at
FROM contact_properties
WHERE team_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListContactPropertiesParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListContactProperties(ctx context.Context, arg ListContactPropertiesParams) ([]ContactProperty, error) {
	rows, err := q.db.Query(ctx, listContactProperties, arg.TeamID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactProperty{}
	for rows.Next() {
		var i ContactProperty
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Key,
			&i.ValueType,
			&i.FallbackString,
			&i.FallbackNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContactPropertyFallback = `-- name: UpdateContactPropertyFallback :one
UPDATE contact_properties
SET fallback_string = $1,
    fallback_number = $2,
    updated_at = now()
WHERE id = $3
  AND team_id = $4
RETURNING id, team_id, key, value_type, fallback_string, fallback_number, created_at, updated_at
`

type UpdateContactPropertyFallbackParams struct {
	FallbackString *string        `db:"fallback_string" json:"fallback_string"`
	FallbackNumber pgtype.Numeric `db:"fallback_number" json:"fallback_number"`
	ID             uuid.UUID      `db:"id" json:"id"`
	TeamID         uuid.UUID      `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateContactPropertyFallback(ctx context.Context, arg UpdateContactPropertyFallbackParams) (ContactProperty, error) {
	row := q.db.QueryRow(ctx, updateContactPropertyFallback,
		arg.FallbackString,
		arg.FallbackNumber,
		arg.ID,
		arg.TeamID,
	)
	var i ContactProperty
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.ValueType,
		&i.FallbackString,
		&i.FallbackNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
