// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (
    team_id,
    email,
    first_name,
    last_name,
    unsubscribed
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, team_id, email, first_name, last_name, unsubscribed, created_at, updated_at
`

type CreateContactParams struct {
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
	Email        string    `db:"email" json:"email"`
	FirstName    *string   `db:"first_name" json:"first_name"`
	LastName     *string   `db:"last_name" json:"last_name"`
	Unsubscribed bool      `db:"unsubscribed" json:"unsubscribed"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.TeamID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Unsubscribed,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Unsubscribed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :one
DELETE FROM contacts
WHERE id = $1
  AND team_id = $2
RETURNING id, team_id, email, first_name, last_name, unsubscribed, created_at, updated_at
`

type DeleteContactParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, deleteContact, arg.ID, arg.TeamID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Unsubscribed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContactPropertyValues = `-- name: DeleteContactPropertyValues :exec
DELETE FROM contact_property_values
WHERE team_id = $1
  AND contact_id = $2
`

type DeleteContactPropertyValuesParams struct {
	TeamID    uuid.UUID `db:"team_id" json:"team_id"`
	ContactID uuid.UUID `db:"contact_id" json:"contact_id"`
}

func (q *Queries) DeleteContactPropertyValues(ctx context.Context, arg DeleteContactPropertyValuesParams) error {
	_, err := q.db.Exec(ctx, deleteContactPropertyValues, arg.TeamID, arg.ContactID)
	return err
}

const getContact = `-- name: GetContact :one
SELECT id, team_id, email, first_name, last_name, unsubscribed, created_at, updated_at
FROM contacts
WHERE id = $1
  AND team_id = $2
`

type GetContactParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, arg.ID, arg.TeamID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Unsubscribed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactByEmail = `-- name: GetContactByEmail :one
SELECT id, team_id, email, first_name, last_name, unsubscribed, created_at, updated_at
FROM contacts
WHERE team_id = $1
  AND lower(email) = lower($2)
`

type GetContactByEmailParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Email  string    `db:"email" json:"email"`
}

func (q *Queries) GetContactByEmail(ctx context.Context, arg GetContactByEmailParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByEmail, arg.TeamID, arg.Email)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Unsubscribed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContactPropertyValues = `-- name: ListContactPropertyValues :many
SELECT
    cpv.contact_id,
    cp.key,
    cp.value_type,
    cpv.string_value,
    cpv.number_value
FROM contact_property_values AS cpv
JOIN contact_properties AS cp
  ON cp.id = cpv.contact_property_id
 AND cp.team_id = cpv.team_id
WHERE cpv.team_id = $1
  AND cpv.contact_id = $2
ORDER BY cp.key
`

type ListContactPropertyValuesParams struct {
	TeamID    uuid.UUID `db:"team_id" json:"team_id"`
	ContactID uuid.UUID `db:"contact_id" json:"contact_id"`
}

type ListContactPropertyValuesRow struct {
	ContactID   uuid.UUID      `db:"contact_id" json:"contact_id"`
	Key         string         `db:"key" json:"key"`
	ValueType   string         `db:"value_type" json:"value_type"`
	StringValue *string        `db:"string_value" json:"string_value"`
	NumberValue pgtype.Numeric `db:"number_value" json:"number_value"`
}

func (q *Queries) ListContactPropertyValues(ctx context.Context, arg ListContactPropertyValuesParams) ([]ListContactPropertyValuesRow, error) {
	rows, err := q.db.Query(ctx, listContactPropertyValues, arg.TeamID, arg.ContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactPropertyValuesRow{}
	for rows.Next() {
		var i ListContactPropertyValuesRow
		if err := rows.Scan(
			&i.ContactID,
			&i.Key,
			&i.ValueType,
			&i.StringValue,
			&i.NumberValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT id, team_id, email, first_name, last_name, unsubscribed, created_at, updated_at
FROM contacts
WHERE team_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListContactsParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts, arg.TeamID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Unsubscribed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET email = $1,
    first_name = $2,
    last_name = $3,
    unsubscribed = $4,
    updated_at = now()
WHERE id = $5
  AND team_id = $6
RETURNING id, team_id, email, first_name, last_name, unsubscribed, created_at, updated_at
`

type UpdateContactParams struct {
	Email        string    `db:"email" json:"email"`
	FirstName    *string   `db:"first_name" json:"first_name"`
	LastName     *string   `db:"last_name" json:"last_name"`
	Unsubscribed bool      `db:"unsubscribed" json:"unsubscribed"`
	ID           uuid.UUID `db:"id" json:"id"`
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Unsubscribed,
		arg.ID,
		arg.TeamID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Unsubscribed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContactNumberPropertyValue = `-- name: UpsertContactNumberPropertyValue :exec
INSERT INTO contact_property_values (
    team_id,
    contact_id,
    contact_property_id,
    value_type,
    number_value
)
SELECT
    $1,
    $2,
    cp.id,
    cp.value_type,
    $3
FROM contact_properties AS cp
WHERE cp.team_id = $1
  AND cp.key = $4
  AND cp.value_type = 'number'
ON CONFLICT (contact_id, contact_property_id)
DO UPDATE SET
    value_type = EXCLUDED.value_type,
    string_value = NULL,
    number_value = EXCLUDED.number_value,
    updated_at = now()
`

type UpsertContactNumberPropertyValueParams struct {
	TeamID        uuid.UUID      `db:"team_id" json:"team_id"`
	ContactID     uuid.UUID      `db:"contact_id" json:"contact_id"`
	PropertyValue pgtype.Numeric `db:"property_value" json:"property_value"`
	PropertyKey   string         `db:"property_key" json:"property_key"`
}

func (q *Queries) UpsertContactNumberPropertyValue(ctx context.Context, arg UpsertContactNumberPropertyValueParams) error {
	_, err := q.db.Exec(ctx, upsertContactNumberPropertyValue,
		arg.TeamID,
		arg.ContactID,
		arg.PropertyValue,
		arg.PropertyKey,
	)
	return err
}

const upsertContactStringPropertyValue = `-- name: UpsertContactStringPropertyValue :exec
INSERT INTO contact_property_values (
    team_id,
    contact_id,
    contact_property_id,
    value_type,
    string_value
)
SELECT
    $1,
    $2,
    cp.id,
    cp.value_type,
    $3
FROM contact_properties AS cp
WHERE cp.team_id = $1
  AND cp.key = $4
  AND cp.value_type = 'string'
ON CONFLICT (contact_id, contact_property_id)
DO UPDATE SET
    value_type = EXCLUDED.value_type,
    string_value = EXCLUDED.string_value,
    number_value = NULL,
    updated_at = now()
`

type UpsertContactStringPropertyValueParams struct {
	TeamID        uuid.UUID `db:"team_id" json:"team_id"`
	ContactID     uuid.UUID `db:"contact_id" json:"contact_id"`
	PropertyValue *string   `db:"property_value" json:"property_value"`
	PropertyKey   string    `db:"property_key" json:"property_key"`
}

func (q *Queries) UpsertContactStringPropertyValue(ctx context.Context, arg UpsertContactStringPropertyValueParams) error {
	_, err := q.db.Exec(ctx, upsertContactStringPropertyValue,
		arg.TeamID,
		arg.ContactID,
		arg.PropertyValue,
		arg.PropertyKey,
	)
	return err
}
