// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_messages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailMessage = `-- name: CreateEmailMessage :one
INSERT INTO email_messages (
    team_id,
    sender_domain_id,
    delivery_provider,
    provider_region,
    message_type,
    from_email,
    from_name,
    reply_to_email,
    to_email,
    to_name,
    subject,
    html_body,
    text_body,
    status,
    metadata,
    recipients,
    headers,
    attachments,
    tags,
    scheduled_at
)
SELECT
    team.id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    'queued',
    $13,
    $14,
    $15,
    $16,
    $17,
    $18
FROM teams AS team
WHERE team.id = $19
  AND team.status = 'active'
RETURNING id, team_id, sender_domain_id, delivery_provider, provider_region, message_type, from_email, from_name, reply_to_email, to_email, to_name, subject, html_body, text_body, status, provider, provider_message_id, error_code, error_message, metadata, recipients, headers, attachments, tags, scheduled_at, queued_at, processing_at, submitted_at, delivered_at, failed_at, created_at, updated_at, current_delivery_attempt_id
`

type CreateEmailMessageParams struct {
	SenderDomainID   *uuid.UUID         `db:"sender_domain_id" json:"sender_domain_id"`
	DeliveryProvider string             `db:"delivery_provider" json:"delivery_provider"`
	ProviderRegion   string             `db:"provider_region" json:"provider_region"`
	MessageType      string             `db:"message_type" json:"message_type"`
	FromEmail        string             `db:"from_email" json:"from_email"`
	FromName         *string            `db:"from_name" json:"from_name"`
	ReplyToEmail     *string            `db:"reply_to_email" json:"reply_to_email"`
	ToEmail          string             `db:"to_email" json:"to_email"`
	ToName           *string            `db:"to_name" json:"to_name"`
	Subject          string             `db:"subject" json:"subject"`
	HtmlBody         *string            `db:"html_body" json:"html_body"`
	TextBody         *string            `db:"text_body" json:"text_body"`
	Metadata         []byte             `db:"metadata" json:"metadata"`
	Recipients       []byte             `db:"recipients" json:"recipients"`
	Headers          []byte             `db:"headers" json:"headers"`
	Attachments      []byte             `db:"attachments" json:"attachments"`
	Tags             []byte             `db:"tags" json:"tags"`
	ScheduledAt      pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	TeamID           uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateEmailMessage(ctx context.Context, arg CreateEmailMessageParams) (EmailMessage, error) {
	row := q.db.QueryRow(ctx, createEmailMessage,
		arg.SenderDomainID,
		arg.DeliveryProvider,
		arg.ProviderRegion,
		arg.MessageType,
		arg.FromEmail,
		arg.FromName,
		arg.ReplyToEmail,
		arg.ToEmail,
		arg.ToName,
		arg.Subject,
		arg.HtmlBody,
		arg.TextBody,
		arg.Metadata,
		arg.Recipients,
		arg.Headers,
		arg.Attachments,
		arg.Tags,
		arg.ScheduledAt,
		arg.TeamID,
	)
	var i EmailMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SenderDomainID,
		&i.DeliveryProvider,
		&i.ProviderRegion,
		&i.MessageType,
		&i.FromEmail,
		&i.FromName,
		&i.ReplyToEmail,
		&i.ToEmail,
		&i.ToName,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
		&i.Provider,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.Recipients,
		&i.Headers,
		&i.Attachments,
		&i.Tags,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.ProcessingAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentDeliveryAttemptID,
	)
	return i, err
}

const getEmailMessage = `-- name: GetEmailMessage :one
SELECT message.id, message.team_id, message.sender_domain_id, message.delivery_provider, message.provider_region, message.message_type, message.from_email, message.from_name, message.reply_to_email, message.to_email, message.to_name, message.subject, message.html_body, message.text_body, message.status, message.provider, message.provider_message_id, message.error_code, message.error_message, message.metadata, message.recipients, message.headers, message.attachments, message.tags, message.scheduled_at, message.queued_at, message.processing_at, message.submitted_at, message.delivered_at, message.failed_at, message.created_at, message.updated_at, message.current_delivery_attempt_id
FROM email_messages AS message
JOIN teams AS team ON team.id = message.team_id
WHERE message.id = $1
  AND message.team_id = $2
  AND team.status = 'active'
`

type GetEmailMessageParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetEmailMessage(ctx context.Context, arg GetEmailMessageParams) (EmailMessage, error) {
	row := q.db.QueryRow(ctx, getEmailMessage, arg.ID, arg.TeamID)
	var i EmailMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SenderDomainID,
		&i.DeliveryProvider,
		&i.ProviderRegion,
		&i.MessageType,
		&i.FromEmail,
		&i.FromName,
		&i.ReplyToEmail,
		&i.ToEmail,
		&i.ToName,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
		&i.Provider,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.Recipients,
		&i.Headers,
		&i.Attachments,
		&i.Tags,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.ProcessingAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentDeliveryAttemptID,
	)
	return i, err
}

const listEmailMessages = `-- name: ListEmailMessages :many
SELECT
    message.id,
    message.team_id,
    message.to_email,
    message.to_name,
    message.subject,
    message.status,
    message.provider,
    message.queued_at,
    message.submitted_at,
    message.delivered_at,
    message.created_at
FROM email_messages AS message
JOIN teams AS team ON team.id = message.team_id
WHERE message.team_id = $1
  AND team.status = 'active'
ORDER BY message.created_at DESC
LIMIT $3
OFFSET $2
`

type ListEmailMessagesParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

type ListEmailMessagesRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
	ToEmail     string             `db:"to_email" json:"to_email"`
	ToName      *string            `db:"to_name" json:"to_name"`
	Subject     string             `db:"subject" json:"subject"`
	Status      string             `db:"status" json:"status"`
	Provider    *string            `db:"provider" json:"provider"`
	QueuedAt    pgtype.Timestamptz `db:"queued_at" json:"queued_at"`
	SubmittedAt pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	DeliveredAt pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListEmailMessages(ctx context.Context, arg ListEmailMessagesParams) ([]ListEmailMessagesRow, error) {
	rows, err := q.db.Query(ctx, listEmailMessages, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmailMessagesRow{}
	for rows.Next() {
		var i ListEmailMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ToEmail,
			&i.ToName,
			&i.Subject,
			&i.Status,
			&i.Provider,
			&i.QueuedAt,
			&i.SubmittedAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
