// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_delivery_attempts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const completeEmailDeliveryAttempt = `-- name: CompleteEmailDeliveryAttempt :execrows
UPDATE email_delivery_attempts
SET status = $1,
    error_code = $2,
    error_message = $3,
    completed_at = now(),
    updated_at = now()
WHERE id = $4
  AND email_message_id = $5
  AND team_id = $6
  AND status IN ('claimed', 'request_started')
`

type CompleteEmailDeliveryAttemptParams struct {
	Status         string    `db:"status" json:"status"`
	ErrorCode      *string   `db:"error_code" json:"error_code"`
	ErrorMessage   *string   `db:"error_message" json:"error_message"`
	ID             uuid.UUID `db:"id" json:"id"`
	EmailMessageID uuid.UUID `db:"email_message_id" json:"email_message_id"`
	TeamID         uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) CompleteEmailDeliveryAttempt(ctx context.Context, arg CompleteEmailDeliveryAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeEmailDeliveryAttempt,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.EmailMessageID,
		arg.TeamID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEmailDeliveryAttempt = `-- name: CreateEmailDeliveryAttempt :one
INSERT INTO email_delivery_attempts (
    email_message_id,
    team_id,
    attempt_number,
    status,
    provider
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, email_message_id, team_id, attempt_number, status, provider, provider_message_id, error_code, error_message, claimed_at, request_started_at, completed_at, created_at, updated_at
`

type CreateEmailDeliveryAttemptParams struct {
	EmailMessageID uuid.UUID `db:"email_message_id" json:"email_message_id"`
	TeamID         uuid.UUID `db:"team_id" json:"team_id"`
	AttemptNumber  int32     `db:"attempt_number" json:"attempt_number"`
	Status         string    `db:"status" json:"status"`
	Provider       string    `db:"provider" json:"provider"`
}

func (q *Queries) CreateEmailDeliveryAttempt(ctx context.Context, arg CreateEmailDeliveryAttemptParams) (EmailDeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, createEmailDeliveryAttempt,
		arg.EmailMessageID,
		arg.TeamID,
		arg.AttemptNumber,
		arg.Status,
		arg.Provider,
	)
	var i EmailDeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.EmailMessageID,
		&i.TeamID,
		&i.AttemptNumber,
		&i.Status,
		&i.Provider,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ClaimedAt,
		&i.RequestStartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const emailDeliveryAttemptExists = `-- name: EmailDeliveryAttemptExists :one
SELECT EXISTS (
    SELECT 1
    FROM email_delivery_attempts
    WHERE id = $1
      AND email_message_id = $2
)
`

type EmailDeliveryAttemptExistsParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	EmailMessageID uuid.UUID `db:"email_message_id" json:"email_message_id"`
}

func (q *Queries) EmailDeliveryAttemptExists(ctx context.Context, arg EmailDeliveryAttemptExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, emailDeliveryAttemptExists, arg.ID, arg.EmailMessageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getEmailDeliveryAttempt = `-- name: GetEmailDeliveryAttempt :one
SELECT id, email_message_id, team_id, attempt_number, status, provider, provider_message_id, error_code, error_message, claimed_at, request_started_at, completed_at, created_at, updated_at
FROM email_delivery_attempts
WHERE id = $1
  AND email_message_id = $2
  AND team_id = $3
`

type GetEmailDeliveryAttemptParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	EmailMessageID uuid.UUID `db:"email_message_id" json:"email_message_id"`
	TeamID         uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetEmailDeliveryAttempt(ctx context.Context, arg GetEmailDeliveryAttemptParams) (EmailDeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, getEmailDeliveryAttempt, arg.ID, arg.EmailMessageID, arg.TeamID)
	var i EmailDeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.EmailMessageID,
		&i.TeamID,
		&i.AttemptNumber,
		&i.Status,
		&i.Provider,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ClaimedAt,
		&i.RequestStartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextEmailDeliveryAttemptNumber = `-- name: GetNextEmailDeliveryAttemptNumber :one
SELECT COALESCE(MAX(attempt_number), 0)::integer + 1
FROM email_delivery_attempts
WHERE email_message_id = $1
`

type GetNextEmailDeliveryAttemptNumberParams struct {
	EmailMessageID uuid.UUID `db:"email_message_id" json:"email_message_id"`
}

func (q *Queries) GetNextEmailDeliveryAttemptNumber(ctx context.Context, arg GetNextEmailDeliveryAttemptNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, getNextEmailDeliveryAttemptNumber, arg.EmailMessageID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listEmailDeliveryAttempts = `-- name: ListEmailDeliveryAttempts :many
SELECT id, email_message_id, team_id, attempt_number, status, provider, provider_message_id, error_code, error_message, claimed_at, request_started_at, completed_at, created_at, updated_at
FROM email_delivery_attempts
WHERE email_message_id = $1
ORDER BY attempt_number DESC
`

type ListEmailDeliveryAttemptsParams struct {
	EmailMessageID uuid.UUID `db:"email_message_id" json:"email_message_id"`
}

func (q *Queries) ListEmailDeliveryAttempts(ctx context.Context, arg ListEmailDeliveryAttemptsParams) ([]EmailDeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listEmailDeliveryAttempts, arg.EmailMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailDeliveryAttempt{}
	for rows.Next() {
		var i EmailDeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.EmailMessageID,
			&i.TeamID,
			&i.AttemptNumber,
			&i.Status,
			&i.Provider,
			&i.ProviderMessageID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.ClaimedAt,
			&i.RequestStartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailDeliveryAttemptRequestStarted = `-- name: MarkEmailDeliveryAttemptRequestStarted :execrows
UPDATE email_delivery_attempts
SET status = 'request_started',
    request_started_at = now(),
    updated_at = now()
WHERE id = $1
  AND email_message_id = $2
  AND team_id = $3
  AND status = 'claimed'
`

type MarkEmailDeliveryAttemptRequestStartedParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	EmailMessageID uuid.UUID `db:"email_message_id" json:"email_message_id"`
	TeamID         uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkEmailDeliveryAttemptRequestStarted(ctx context.Context, arg MarkEmailDeliveryAttemptRequestStartedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailDeliveryAttemptRequestStarted, arg.ID, arg.EmailMessageID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markEmailDeliveryAttemptSubmitted = `-- name: MarkEmailDeliveryAttemptSubmitted :execrows
UPDATE email_delivery_attempts
SET status = 'submitted',
    provider = $1,
    provider_message_id = $2,
    completed_at = now(),
    error_code = NULL,
    error_message = NULL,
    updated_at = now()
WHERE id = $3
  AND email_message_id = $4
  AND team_id = $5
  AND status IN ('claimed', 'request_started', 'submission_unknown')
`

type MarkEmailDeliveryAttemptSubmittedParams struct {
	Provider          string    `db:"provider" json:"provider"`
	ProviderMessageID *string   `db:"provider_message_id" json:"provider_message_id"`
	ID                uuid.UUID `db:"id" json:"id"`
	EmailMessageID    uuid.UUID `db:"email_message_id" json:"email_message_id"`
	TeamID            uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkEmailDeliveryAttemptSubmitted(ctx context.Context, arg MarkEmailDeliveryAttemptSubmittedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailDeliveryAttemptSubmitted,
		arg.Provider,
		arg.ProviderMessageID,
		arg.ID,
		arg.EmailMessageID,
		arg.TeamID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
