// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message_templates.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMessageTemplate = `-- name: CreateMessageTemplate :one
INSERT INTO message_templates (team_id, name, alias)
VALUES ($1, $2, $3)
RETURNING id, team_id, name, alias, current_version_id, published_version_id, next_version_number, published_at, created_at, updated_at, deleted_at
`

type CreateMessageTemplateParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Name   string    `db:"name" json:"name"`
	Alias  string    `db:"alias" json:"alias"`
}

func (q *Queries) CreateMessageTemplate(ctx context.Context, arg CreateMessageTemplateParams) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, createMessageTemplate, arg.TeamID, arg.Name, arg.Alias)
	var i MessageTemplate
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Alias,
		&i.CurrentVersionID,
		&i.PublishedVersionID,
		&i.NextVersionNumber,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMessageTemplatePublication = `-- name: CreateMessageTemplatePublication :one
INSERT INTO message_template_publications (team_id, template_id, version_id)
VALUES ($1, $2, $3)
RETURNING id, team_id, template_id, version_id, published_at
`

type CreateMessageTemplatePublicationParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	TemplateID uuid.UUID `db:"template_id" json:"template_id"`
	VersionID  uuid.UUID `db:"version_id" json:"version_id"`
}

func (q *Queries) CreateMessageTemplatePublication(ctx context.Context, arg CreateMessageTemplatePublicationParams) (MessageTemplatePublication, error) {
	row := q.db.QueryRow(ctx, createMessageTemplatePublication, arg.TeamID, arg.TemplateID, arg.VersionID)
	var i MessageTemplatePublication
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.TemplateID,
		&i.VersionID,
		&i.PublishedAt,
	)
	return i, err
}

const createMessageTemplateVersion = `-- name: CreateMessageTemplateVersion :one
INSERT INTO message_template_versions (
    team_id, template_id, version_number,
    from_email, from_name, reply_to_email,
    subject, html_body, text_body, variables,
    based_on_version_id, change_note
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12
)
RETURNING id, team_id, template_id, version_number, from_email, from_name, reply_to_email, subject, html_body, text_body, variables, based_on_version_id, change_note, created_at
`

type CreateMessageTemplateVersionParams struct {
	TeamID           uuid.UUID  `db:"team_id" json:"team_id"`
	TemplateID       uuid.UUID  `db:"template_id" json:"template_id"`
	VersionNumber    int32      `db:"version_number" json:"version_number"`
	FromEmail        *string    `db:"from_email" json:"from_email"`
	FromName         *string    `db:"from_name" json:"from_name"`
	ReplyToEmail     *string    `db:"reply_to_email" json:"reply_to_email"`
	Subject          string     `db:"subject" json:"subject"`
	HtmlBody         string     `db:"html_body" json:"html_body"`
	TextBody         *string    `db:"text_body" json:"text_body"`
	Variables        []byte     `db:"variables" json:"variables"`
	BasedOnVersionID *uuid.UUID `db:"based_on_version_id" json:"based_on_version_id"`
	ChangeNote       *string    `db:"change_note" json:"change_note"`
}

func (q *Queries) CreateMessageTemplateVersion(ctx context.Context, arg CreateMessageTemplateVersionParams) (MessageTemplateVersion, error) {
	row := q.db.QueryRow(ctx, createMessageTemplateVersion,
		arg.TeamID,
		arg.TemplateID,
		arg.VersionNumber,
		arg.FromEmail,
		arg.FromName,
		arg.ReplyToEmail,
		arg.Subject,
		arg.HtmlBody,
		arg.TextBody,
		arg.Variables,
		arg.BasedOnVersionID,
		arg.ChangeNote,
	)
	var i MessageTemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.TemplateID,
		&i.VersionNumber,
		&i.FromEmail,
		&i.FromName,
		&i.ReplyToEmail,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Variables,
		&i.BasedOnVersionID,
		&i.ChangeNote,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageTemplateByAlias = `-- name: GetMessageTemplateByAlias :one
SELECT id, team_id, name, alias, current_version_id, published_version_id, next_version_number, published_at, created_at, updated_at, deleted_at
FROM message_templates
WHERE team_id = $1
  AND lower(alias) = lower($2)
  AND deleted_at IS NULL
`

type GetMessageTemplateByAliasParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Alias  string    `db:"alias" json:"alias"`
}

func (q *Queries) GetMessageTemplateByAlias(ctx context.Context, arg GetMessageTemplateByAliasParams) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, getMessageTemplateByAlias, arg.TeamID, arg.Alias)
	var i MessageTemplate
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Alias,
		&i.CurrentVersionID,
		&i.PublishedVersionID,
		&i.NextVersionNumber,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMessageTemplateByID = `-- name: GetMessageTemplateByID :one
SELECT id, team_id, name, alias, current_version_id, published_version_id, next_version_number, published_at, created_at, updated_at, deleted_at
FROM message_templates
WHERE id = $1
  AND team_id = $2
  AND deleted_at IS NULL
`

type GetMessageTemplateByIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetMessageTemplateByID(ctx context.Context, arg GetMessageTemplateByIDParams) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, getMessageTemplateByID, arg.ID, arg.TeamID)
	var i MessageTemplate
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Alias,
		&i.CurrentVersionID,
		&i.PublishedVersionID,
		&i.NextVersionNumber,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMessageTemplateVersion = `-- name: GetMessageTemplateVersion :one
SELECT id, team_id, template_id, version_number, from_email, from_name, reply_to_email, subject, html_body, text_body, variables, based_on_version_id, change_note, created_at
FROM message_template_versions
WHERE id = $1
  AND template_id = $2
  AND team_id = $3
`

type GetMessageTemplateVersionParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	TemplateID uuid.UUID `db:"template_id" json:"template_id"`
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetMessageTemplateVersion(ctx context.Context, arg GetMessageTemplateVersionParams) (MessageTemplateVersion, error) {
	row := q.db.QueryRow(ctx, getMessageTemplateVersion, arg.ID, arg.TemplateID, arg.TeamID)
	var i MessageTemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.TemplateID,
		&i.VersionNumber,
		&i.FromEmail,
		&i.FromName,
		&i.ReplyToEmail,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Variables,
		&i.BasedOnVersionID,
		&i.ChangeNote,
		&i.CreatedAt,
	)
	return i, err
}

const listMessageTemplateVersions = `-- name: ListMessageTemplateVersions :many
SELECT id, team_id, template_id, version_number, from_email, from_name, reply_to_email, subject, html_body, text_body, variables, based_on_version_id, change_note, created_at
FROM message_template_versions
WHERE team_id = $1
  AND template_id = $2
ORDER BY version_number DESC
LIMIT $4
OFFSET $3
`

type ListMessageTemplateVersionsParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	TemplateID uuid.UUID `db:"template_id" json:"template_id"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListMessageTemplateVersions(ctx context.Context, arg ListMessageTemplateVersionsParams) ([]MessageTemplateVersion, error) {
	rows, err := q.db.Query(ctx, listMessageTemplateVersions,
		arg.TeamID,
		arg.TemplateID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageTemplateVersion{}
	for rows.Next() {
		var i MessageTemplateVersion
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.TemplateID,
			&i.VersionNumber,
			&i.FromEmail,
			&i.FromName,
			&i.ReplyToEmail,
			&i.Subject,
			&i.HtmlBody,
			&i.TextBody,
			&i.Variables,
			&i.BasedOnVersionID,
			&i.ChangeNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageTemplates = `-- name: ListMessageTemplates :many
SELECT id, team_id, name, alias, current_version_id, published_version_id, next_version_number, published_at, created_at, updated_at, deleted_at
FROM message_templates
WHERE team_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListMessageTemplatesParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListMessageTemplates(ctx context.Context, arg ListMessageTemplatesParams) ([]MessageTemplate, error) {
	rows, err := q.db.Query(ctx, listMessageTemplates, arg.TeamID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageTemplate{}
	for rows.Next() {
		var i MessageTemplate
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Alias,
			&i.CurrentVersionID,
			&i.PublishedVersionID,
			&i.NextVersionNumber,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMessageTemplate = `-- name: LockMessageTemplate :one
SELECT id, team_id, name, alias, current_version_id, published_version_id, next_version_number, published_at, created_at, updated_at, deleted_at
FROM message_templates
WHERE id = $1
  AND team_id = $2
  AND deleted_at IS NULL
FOR UPDATE
`

type LockMessageTemplateParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) LockMessageTemplate(ctx context.Context, arg LockMessageTemplateParams) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, lockMessageTemplate, arg.ID, arg.TeamID)
	var i MessageTemplate
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Alias,
		&i.CurrentVersionID,
		&i.PublishedVersionID,
		&i.NextVersionNumber,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const publishMessageTemplateVersion = `-- name: PublishMessageTemplateVersion :one
UPDATE message_templates
SET published_version_id = $1,
    published_at = now(),
    updated_at = now()
WHERE id = $2
  AND team_id = $3
  AND deleted_at IS NULL
RETURNING id, team_id, name, alias, current_version_id, published_version_id, next_version_number, published_at, created_at, updated_at, deleted_at
`

type PublishMessageTemplateVersionParams struct {
	VersionID *uuid.UUID `db:"version_id" json:"version_id"`
	ID        uuid.UUID  `db:"id" json:"id"`
	TeamID    uuid.UUID  `db:"team_id" json:"team_id"`
}

func (q *Queries) PublishMessageTemplateVersion(ctx context.Context, arg PublishMessageTemplateVersionParams) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, publishMessageTemplateVersion, arg.VersionID, arg.ID, arg.TeamID)
	var i MessageTemplate
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Alias,
		&i.CurrentVersionID,
		&i.PublishedVersionID,
		&i.NextVersionNumber,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setMessageTemplateCurrentVersion = `-- name: SetMessageTemplateCurrentVersion :one
UPDATE message_templates
SET current_version_id = $1,
    next_version_number = next_version_number + 1,
    updated_at = now()
WHERE id = $2
  AND team_id = $3
  AND deleted_at IS NULL
RETURNING id, team_id, name, alias, current_version_id, published_version_id, next_version_number, published_at, created_at, updated_at, deleted_at
`

type SetMessageTemplateCurrentVersionParams struct {
	VersionID *uuid.UUID `db:"version_id" json:"version_id"`
	ID        uuid.UUID  `db:"id" json:"id"`
	TeamID    uuid.UUID  `db:"team_id" json:"team_id"`
}

func (q *Queries) SetMessageTemplateCurrentVersion(ctx context.Context, arg SetMessageTemplateCurrentVersionParams) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, setMessageTemplateCurrentVersion, arg.VersionID, arg.ID, arg.TeamID)
	var i MessageTemplate
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Alias,
		&i.CurrentVersionID,
		&i.PublishedVersionID,
		&i.NextVersionNumber,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteMessageTemplate = `-- name: SoftDeleteMessageTemplate :one
UPDATE message_templates
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND deleted_at IS NULL
RETURNING id, team_id, name, alias, current_version_id, published_version_id, next_version_number, published_at, created_at, updated_at, deleted_at
`

type SoftDeleteMessageTemplateParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) SoftDeleteMessageTemplate(ctx context.Context, arg SoftDeleteMessageTemplateParams) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, softDeleteMessageTemplate, arg.ID, arg.TeamID)
	var i MessageTemplate
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Alias,
		&i.CurrentVersionID,
		&i.PublishedVersionID,
		&i.NextVersionNumber,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateMessageTemplateMetadata = `-- name: UpdateMessageTemplateMetadata :one
UPDATE message_templates
SET name = $1,
    alias = $2,
    updated_at = now()
WHERE id = $3
  AND team_id = $4
  AND deleted_at IS NULL
RETURNING id, team_id, name, alias, current_version_id, published_version_id, next_version_number, published_at, created_at, updated_at, deleted_at
`

type UpdateMessageTemplateMetadataParams struct {
	Name   string    `db:"name" json:"name"`
	Alias  string    `db:"alias" json:"alias"`
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateMessageTemplateMetadata(ctx context.Context, arg UpdateMessageTemplateMetadataParams) (MessageTemplate, error) {
	row := q.db.QueryRow(ctx, updateMessageTemplateMetadata,
		arg.Name,
		arg.Alias,
		arg.ID,
		arg.TeamID,
	)
	var i MessageTemplate
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Alias,
		&i.CurrentVersionID,
		&i.PublishedVersionID,
		&i.NextVersionNumber,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
