// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	TeamID         *uuid.UUID         `db:"team_id" json:"team_id"`
	ActorType      string             `db:"actor_type" json:"actor_type"`
	ActorUserID    *uuid.UUID         `db:"actor_user_id" json:"actor_user_id"`
	ActorSessionID *string            `db:"actor_session_id" json:"actor_session_id"`
	ActorTokenID   *uuid.UUID         `db:"actor_token_id" json:"actor_token_id"`
	Action         string             `db:"action" json:"action"`
	ResourceType   string             `db:"resource_type" json:"resource_type"`
	ResourceID     string             `db:"resource_id" json:"resource_id"`
	Outcome        string             `db:"outcome" json:"outcome"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	RequestID      *string            `db:"request_id" json:"request_id"`
	IpAddress      *string            `db:"ip_address" json:"ip_address"`
	UserAgent      *string            `db:"user_agent" json:"user_agent"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuthenticationChallenge struct {
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	UserID     *uuid.UUID         `db:"user_id" json:"user_id"`
	Purpose    string             `db:"purpose" json:"purpose"`
	State      []byte             `db:"state" json:"state"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type BillingMarket struct {
	Code      string `db:"code" json:"code"`
	Currency  string `db:"currency" json:"currency"`
	IsEnabled bool   `db:"is_enabled" json:"is_enabled"`
}

type Currency struct {
	Code      string `db:"code" json:"code"`
	MinorUnit int16  `db:"minor_unit" json:"minor_unit"`
	IsEnabled bool   `db:"is_enabled" json:"is_enabled"`
}

type EmailDeliveryAttempt struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	EmailMessageID    uuid.UUID          `db:"email_message_id" json:"email_message_id"`
	TeamID            uuid.UUID          `db:"team_id" json:"team_id"`
	AttemptNumber     int32              `db:"attempt_number" json:"attempt_number"`
	Status            string             `db:"status" json:"status"`
	Provider          string             `db:"provider" json:"provider"`
	ProviderMessageID *string            `db:"provider_message_id" json:"provider_message_id"`
	ErrorCode         *string            `db:"error_code" json:"error_code"`
	ErrorMessage      *string            `db:"error_message" json:"error_message"`
	ClaimedAt         pgtype.Timestamptz `db:"claimed_at" json:"claimed_at"`
	RequestStartedAt  pgtype.Timestamptz `db:"request_started_at" json:"request_started_at"`
	CompletedAt       pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EmailMessage struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	TeamID                   uuid.UUID          `db:"team_id" json:"team_id"`
	SenderDomainID           *uuid.UUID         `db:"sender_domain_id" json:"sender_domain_id"`
	DeliveryProvider         string             `db:"delivery_provider" json:"delivery_provider"`
	ProviderRegion           string             `db:"provider_region" json:"provider_region"`
	MessageType              string             `db:"message_type" json:"message_type"`
	FromEmail                string             `db:"from_email" json:"from_email"`
	FromName                 *string            `db:"from_name" json:"from_name"`
	ReplyToEmail             *string            `db:"reply_to_email" json:"reply_to_email"`
	ToEmail                  string             `db:"to_email" json:"to_email"`
	ToName                   *string            `db:"to_name" json:"to_name"`
	Subject                  string             `db:"subject" json:"subject"`
	HtmlBody                 *string            `db:"html_body" json:"html_body"`
	TextBody                 *string            `db:"text_body" json:"text_body"`
	Status                   string             `db:"status" json:"status"`
	Provider                 *string            `db:"provider" json:"provider"`
	ProviderMessageID        *string            `db:"provider_message_id" json:"provider_message_id"`
	ErrorCode                *string            `db:"error_code" json:"error_code"`
	ErrorMessage             *string            `db:"error_message" json:"error_message"`
	Metadata                 []byte             `db:"metadata" json:"metadata"`
	Recipients               []byte             `db:"recipients" json:"recipients"`
	Headers                  []byte             `db:"headers" json:"headers"`
	Attachments              []byte             `db:"attachments" json:"attachments"`
	Tags                     []byte             `db:"tags" json:"tags"`
	ScheduledAt              pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	QueuedAt                 pgtype.Timestamptz `db:"queued_at" json:"queued_at"`
	ProcessingAt             pgtype.Timestamptz `db:"processing_at" json:"processing_at"`
	SubmittedAt              pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	DeliveredAt              pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	FailedAt                 pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CurrentDeliveryAttemptID *uuid.UUID         `db:"current_delivery_attempt_id" json:"current_delivery_attempt_id"`
}

type EmailProviderEvent struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	EmailMessageID         *uuid.UUID         `db:"email_message_id" json:"email_message_id"`
	Provider               string             `db:"provider" json:"provider"`
	Transport              string             `db:"transport" json:"transport"`
	ProviderNotificationID string             `db:"provider_notification_id" json:"provider_notification_id"`
	ProviderMessageID      string             `db:"provider_message_id" json:"provider_message_id"`
	EventType              string             `db:"event_type" json:"event_type"`
	OccurredAt             pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ReceivedAt             pgtype.Timestamptz `db:"received_at" json:"received_at"`
	NormalizedPayload      []byte             `db:"normalized_payload" json:"normalized_payload"`
	ProviderPayload        []byte             `db:"provider_payload" json:"provider_payload"`
	ProcessedAt            pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	AttemptCount           int32              `db:"attempt_count" json:"attempt_count"`
	NextAttemptAt          pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LastAttemptAt          pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	LastError              *string            `db:"last_error" json:"last_error"`
	DeadLetteredAt         pgtype.Timestamptz `db:"dead_lettered_at" json:"dead_lettered_at"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type EmailRecipient struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	EmailMessageID     uuid.UUID          `db:"email_message_id" json:"email_message_id"`
	RecipientEmail     string             `db:"recipient_email" json:"recipient_email"`
	RecipientType      string             `db:"recipient_type" json:"recipient_type"`
	Status             string             `db:"status" json:"status"`
	LastEventType      *string            `db:"last_event_type" json:"last_event_type"`
	LastEventAt        pgtype.Timestamptz `db:"last_event_at" json:"last_event_at"`
	LastAction         *string            `db:"last_action" json:"last_action"`
	LastStatusCode     *string            `db:"last_status_code" json:"last_status_code"`
	LastDiagnosticCode *string            `db:"last_diagnostic_code" json:"last_diagnostic_code"`
	DeliveredAt        pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	FailedAt           pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
	ErrorCode          *string            `db:"error_code" json:"error_code"`
	ErrorMessage       *string            `db:"error_message" json:"error_message"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EmailTenant struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	TeamID           uuid.UUID          `db:"team_id" json:"team_id"`
	Provider         string             `db:"provider" json:"provider"`
	Region           string             `db:"region" json:"region"`
	ExternalName     string             `db:"external_name" json:"external_name"`
	ExternalID       *string            `db:"external_id" json:"external_id"`
	TenantArn        *string            `db:"tenant_arn" json:"tenant_arn"`
	Status           string             `db:"status" json:"status"`
	SuppressionScope string             `db:"suppression_scope" json:"suppression_scope"`
	ReputationPolicy string             `db:"reputation_policy" json:"reputation_policy"`
	FailureReason    *string            `db:"failure_reason" json:"failure_reason"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type IdempotencyKey struct {
	Scope               string             `db:"scope" json:"scope"`
	IdempotencyKey      string             `db:"idempotency_key" json:"idempotency_key"`
	Method              string             `db:"method" json:"method"`
	Path                string             `db:"path" json:"path"`
	RequestHash         string             `db:"request_hash" json:"request_hash"`
	Status              string             `db:"status" json:"status"`
	ResponseStatus      *int32             `db:"response_status" json:"response_status"`
	ResponseBody        []byte             `db:"response_body" json:"response_body"`
	ResponseContentType *string            `db:"response_content_type" json:"response_content_type"`
	ResponseHeaders     []byte             `db:"response_headers" json:"response_headers"`
	LockedUntil         pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	CompletedAt         pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OauthIdentity struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	Provider    string             `db:"provider" json:"provider"`
	ProviderUid string             `db:"provider_uid" json:"provider_uid"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type OutboxEvent struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Subject       string             `db:"subject" json:"subject"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	Payload       []byte             `db:"payload" json:"payload"`
	Headers       []byte             `db:"headers" json:"headers"`
	AvailableAt   pgtype.Timestamptz `db:"available_at" json:"available_at"`
	PublishedAt   pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Attempts      int32              `db:"attempts" json:"attempts"`
	LastError     *string            `db:"last_error" json:"last_error"`
	LockedAt      pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LockedBy      *string            `db:"locked_by" json:"locked_by"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProcessedEvent struct {
	ConsumerName string             `db:"consumer_name" json:"consumer_name"`
	EventID      uuid.UUID          `db:"event_id" json:"event_id"`
	ProcessedAt  pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	Metadata     []byte             `db:"metadata" json:"metadata"`
}

type ProductRate struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	Product        string             `db:"product" json:"product"`
	Meter          string             `db:"meter" json:"meter"`
	BillingMarket  string             `db:"billing_market" json:"billing_market"`
	Tier           string             `db:"tier" json:"tier"`
	Currency       string             `db:"currency" json:"currency"`
	CostUnits      int64              `db:"cost_units" json:"cost_units"`
	EffectiveFrom  pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RecoveryCode struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	CodeHash  string             `db:"code_hash" json:"code_hash"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SenderDomain struct {
	ID                        uuid.UUID          `db:"id" json:"id"`
	TeamID                    uuid.UUID          `db:"team_id" json:"team_id"`
	Domain                    string             `db:"domain" json:"domain"`
	Provider                  string             `db:"provider" json:"provider"`
	ProviderRegion            string             `db:"provider_region" json:"provider_region"`
	Status                    string             `db:"status" json:"status"`
	VerificationRecords       []byte             `db:"verification_records" json:"verification_records"`
	FailureReason             *string            `db:"failure_reason" json:"failure_reason"`
	LastCheckedAt             pgtype.Timestamptz `db:"last_checked_at" json:"last_checked_at"`
	NextCheckAt               pgtype.Timestamptz `db:"next_check_at" json:"next_check_at"`
	VerificationAttempts      int32              `db:"verification_attempts" json:"verification_attempts"`
	ReconcileLockedAt         pgtype.Timestamptz `db:"reconcile_locked_at" json:"reconcile_locked_at"`
	ReconcileLockedBy         *string            `db:"reconcile_locked_by" json:"reconcile_locked_by"`
	HealthStatus              string             `db:"health_status" json:"health_status"`
	ConsecutiveHealthFailures int32              `db:"consecutive_health_failures" json:"consecutive_health_failures"`
	LastHealthCheckedAt       pgtype.Timestamptz `db:"last_health_checked_at" json:"last_health_checked_at"`
	LastHealthFailureAt       pgtype.Timestamptz `db:"last_health_failure_at" json:"last_health_failure_at"`
	VerifiedAt                pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	DisabledAt                pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	CreatedBy                 *uuid.UUID         `db:"created_by" json:"created_by"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SenderID struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	TeamID          uuid.UUID          `db:"team_id" json:"team_id"`
	Name            string             `db:"name" json:"name"`
	CountryCode     string             `db:"country_code" json:"country_code"`
	Purpose         string             `db:"purpose" json:"purpose"`
	Status          string             `db:"status" json:"status"`
	Provider        *string            `db:"provider" json:"provider"`
	RejectionReason *string            `db:"rejection_reason" json:"rejection_reason"`
	ApprovedAt      pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	RejectedAt      pgtype.Timestamptz `db:"rejected_at" json:"rejected_at"`
	SuspendedAt     pgtype.Timestamptz `db:"suspended_at" json:"suspended_at"`
	CreatedBy       *uuid.UUID         `db:"created_by" json:"created_by"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Session struct {
	ID                   string             `db:"id" json:"id"`
	UserID               uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash            string             `db:"token_hash" json:"token_hash"`
	UserAgent            *string            `db:"user_agent" json:"user_agent"`
	IpAddress            *string            `db:"ip_address" json:"ip_address"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt           pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	CredentialVersion    int64              `db:"credential_version" json:"credential_version"`
	AuthenticationMethod string             `db:"authentication_method" json:"authentication_method"`
	AssuranceLevel       string             `db:"assurance_level" json:"assurance_level"`
	AuthenticatedAt      pgtype.Timestamptz `db:"authenticated_at" json:"authenticated_at"`
	MfaCompletedAt       pgtype.Timestamptz `db:"mfa_completed_at" json:"mfa_completed_at"`
}

type SmsMessage struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	TeamID             uuid.UUID          `db:"team_id" json:"team_id"`
	SenderID           *uuid.UUID         `db:"sender_id" json:"sender_id"`
	ToNumber           string             `db:"to_number" json:"to_number"`
	FromName           string             `db:"from_name" json:"from_name"`
	Body               string             `db:"body" json:"body"`
	Status             string             `db:"status" json:"status"`
	ProviderID         *string            `db:"provider_id" json:"provider_id"`
	ProviderMessageID  *string            `db:"provider_message_id" json:"provider_message_id"`
	Segments           int32              `db:"segments" json:"segments"`
	ErrorMessage       *string            `db:"error_message" json:"error_message"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
	Tags               []byte             `db:"tags" json:"tags"`
	ScheduledAt        pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	SubmittedAt        pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	DeliveredAt        pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DestinationCountry string             `db:"destination_country" json:"destination_country"`
}

type SmsRate struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	BillingMarket      string             `db:"billing_market" json:"billing_market"`
	DestinationCountry string             `db:"destination_country" json:"destination_country"`
	Provider           string             `db:"provider" json:"provider"`
	RouteType          string             `db:"route_type" json:"route_type"`
	Tier               string             `db:"tier" json:"tier"`
	Currency           string             `db:"currency" json:"currency"`
	CostUnits          int64              `db:"cost_units" json:"cost_units"`
	EffectiveFrom      pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil     pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Team struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	MarketCode string             `db:"market_code" json:"market_code"`
	Phone      string             `db:"phone" json:"phone"`
	Address    string             `db:"address" json:"address"`
	Website    *string            `db:"website" json:"website"`
	Status     string             `db:"status" json:"status"`
	CreatedBy  *uuid.UUID         `db:"created_by" json:"created_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TeamInvitation struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TeamID     uuid.UUID          `db:"team_id" json:"team_id"`
	Email      string             `db:"email" json:"email"`
	Role       string             `db:"role" json:"role"`
	Status     string             `db:"status" json:"status"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	InvitedBy  *uuid.UUID         `db:"invited_by" json:"invited_by"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	DeclinedAt pgtype.Timestamptz `db:"declined_at" json:"declined_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TeamMember struct {
	TeamID    uuid.UUID          `db:"team_id" json:"team_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Role      string             `db:"role" json:"role"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TeamToken struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
	Name        string             `db:"name" json:"name"`
	TokenHash   string             `db:"token_hash" json:"token_hash"`
	TokenPrefix string             `db:"token_prefix" json:"token_prefix"`
	Permissions []string           `db:"permissions" json:"permissions"`
	CreatedBy   *uuid.UUID         `db:"created_by" json:"created_by"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	LastUsedAt  pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TeamWallet struct {
	TeamID        uuid.UUID          `db:"team_id" json:"team_id"`
	BillingMarket string             `db:"billing_market" json:"billing_market"`
	Currency      string             `db:"currency" json:"currency"`
	BalanceUnits  int64              `db:"balance_units" json:"balance_units"`
	Tier          string             `db:"tier" json:"tier"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TotpCredential struct {
	UserID           uuid.UUID          `db:"user_id" json:"user_id"`
	SecretCiphertext []byte             `db:"secret_ciphertext" json:"secret_ciphertext"`
	VerifiedAt       pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	LastUsedStep     *int64             `db:"last_used_step" json:"last_used_step"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UsageAllowance struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	TeamID           uuid.UUID          `db:"team_id" json:"team_id"`
	Meter            string             `db:"meter" json:"meter"`
	PeriodStart      pgtype.Timestamptz `db:"period_start" json:"period_start"`
	PeriodEnd        pgtype.Timestamptz `db:"period_end" json:"period_end"`
	IncludedQuantity int64              `db:"included_quantity" json:"included_quantity"`
	ConsumedQuantity int64              `db:"consumed_quantity" json:"consumed_quantity"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UsageAuthorization struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	TeamID             uuid.UUID          `db:"team_id" json:"team_id"`
	Product            string             `db:"product" json:"product"`
	Meter              string             `db:"meter" json:"meter"`
	ReferenceID        string             `db:"reference_id" json:"reference_id"`
	UsageAllowanceID   *uuid.UUID         `db:"usage_allowance_id" json:"usage_allowance_id"`
	SmsRateID          *uuid.UUID         `db:"sms_rate_id" json:"sms_rate_id"`
	ProductRateID      *uuid.UUID         `db:"product_rate_id" json:"product_rate_id"`
	BillingMarket      string             `db:"billing_market" json:"billing_market"`
	DestinationCountry *string            `db:"destination_country" json:"destination_country"`
	Provider           *string            `db:"provider" json:"provider"`
	RouteType          *string            `db:"route_type" json:"route_type"`
	TotalQuantity      int64              `db:"total_quantity" json:"total_quantity"`
	AllowanceQuantity  int64              `db:"allowance_quantity" json:"allowance_quantity"`
	BillableQuantity   int64              `db:"billable_quantity" json:"billable_quantity"`
	UnitCostUnits      int64              `db:"unit_cost_units" json:"unit_cost_units"`
	AmountUnits        int64              `db:"amount_units" json:"amount_units"`
	Currency           string             `db:"currency" json:"currency"`
	Tier               string             `db:"tier" json:"tier"`
	PricedAt           pgtype.Timestamptz `db:"priced_at" json:"priced_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	Email             string             `db:"email" json:"email"`
	EmailVerified     bool               `db:"email_verified" json:"email_verified"`
	Name              string             `db:"name" json:"name"`
	PasswordHash      *string            `db:"password_hash" json:"password_hash"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CredentialVersion int64              `db:"credential_version" json:"credential_version"`
	SecurityUpdatedAt pgtype.Timestamptz `db:"security_updated_at" json:"security_updated_at"`
}

type Verification struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	TeamID              uuid.UUID          `db:"team_id" json:"team_id"`
	ServiceID           uuid.UUID          `db:"service_id" json:"service_id"`
	Channel             string             `db:"channel" json:"channel"`
	Recipient           string             `db:"recipient" json:"recipient"`
	RecipientNormalized string             `db:"recipient_normalized" json:"recipient_normalized"`
	Status              string             `db:"status" json:"status"`
	Locale              *string            `db:"locale" json:"locale"`
	Metadata            []byte             `db:"metadata" json:"metadata"`
	AttemptCount        int32              `db:"attempt_count" json:"attempt_count"`
	ResendCount         int32              `db:"resend_count" json:"resend_count"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ApprovedAt          pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ExpiredAt           pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	CanceledAt          pgtype.Timestamptz `db:"canceled_at" json:"canceled_at"`
	FailedAt            pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type VerificationAttempt struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	TeamID         uuid.UUID          `db:"team_id" json:"team_id"`
	VerificationID uuid.UUID          `db:"verification_id" json:"verification_id"`
	ChallengeID    uuid.UUID          `db:"challenge_id" json:"challenge_id"`
	Result         string             `db:"result" json:"result"`
	IpAddressHash  []byte             `db:"ip_address_hash" json:"ip_address_hash"`
	UserAgent      *string            `db:"user_agent" json:"user_agent"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	AttemptedAt    pgtype.Timestamptz `db:"attempted_at" json:"attempted_at"`
}

type VerificationChallenge struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	TeamID           uuid.UUID          `db:"team_id" json:"team_id"`
	VerificationID   uuid.UUID          `db:"verification_id" json:"verification_id"`
	Sequence         int32              `db:"sequence" json:"sequence"`
	CodeHmac         []byte             `db:"code_hmac" json:"code_hmac"`
	Status           string             `db:"status" json:"status"`
	Channel          string             `db:"channel" json:"channel"`
	EmailMessageID   *uuid.UUID         `db:"email_message_id" json:"email_message_id"`
	SmsMessageID     *uuid.UUID         `db:"sms_message_id" json:"sms_message_id"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	SupersededAt     pgtype.Timestamptz `db:"superseded_at" json:"superseded_at"`
	DispatchedAt     pgtype.Timestamptz `db:"dispatched_at" json:"dispatched_at"`
	DeliveryFailedAt pgtype.Timestamptz `db:"delivery_failed_at" json:"delivery_failed_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type VerificationService struct {
	ID                    uuid.UUID          `db:"id" json:"id"`
	TeamID                uuid.UUID          `db:"team_id" json:"team_id"`
	Key                   string             `db:"key" json:"key"`
	Name                  string             `db:"name" json:"name"`
	DefaultChannel        string             `db:"default_channel" json:"default_channel"`
	CodeLength            int32              `db:"code_length" json:"code_length"`
	TtlSeconds            int32              `db:"ttl_seconds" json:"ttl_seconds"`
	MaxAttempts           int32              `db:"max_attempts" json:"max_attempts"`
	ResendCooldownSeconds int32              `db:"resend_cooldown_seconds" json:"resend_cooldown_seconds"`
	MaxResends            int32              `db:"max_resends" json:"max_resends"`
	Enabled               bool               `db:"enabled" json:"enabled"`
	Metadata              []byte             `db:"metadata" json:"metadata"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type VerificationToken struct {
	Identifier string             `db:"identifier" json:"identifier"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WalletLedger struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	TeamID               uuid.UUID          `db:"team_id" json:"team_id"`
	UsageAuthorizationID *uuid.UUID         `db:"usage_authorization_id" json:"usage_authorization_id"`
	AmountUnits          int64              `db:"amount_units" json:"amount_units"`
	TransactionType      string             `db:"transaction_type" json:"transaction_type"`
	ReferenceID          string             `db:"reference_id" json:"reference_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WebhookDelivery struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	EventID        uuid.UUID          `db:"event_id" json:"event_id"`
	EndpointID     uuid.UUID          `db:"endpoint_id" json:"endpoint_id"`
	Status         string             `db:"status" json:"status"`
	AttemptCount   int32              `db:"attempt_count" json:"attempt_count"`
	ReplayCount    int32              `db:"replay_count" json:"replay_count"`
	NextAttemptAt  pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LastAttemptAt  pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	LastReplayedAt pgtype.Timestamptz `db:"last_replayed_at" json:"last_replayed_at"`
	ResponseStatus *int32             `db:"response_status" json:"response_status"`
	ResponseBody   *string            `db:"response_body" json:"response_body"`
	LastError      *string            `db:"last_error" json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	LockedAt       pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LockedBy       *string            `db:"locked_by" json:"locked_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WebhookDeliveryAttempt struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	DeliveryID       uuid.UUID          `db:"delivery_id" json:"delivery_id"`
	AttemptNumber    int32              `db:"attempt_number" json:"attempt_number"`
	Outcome          string             `db:"outcome" json:"outcome"`
	RequestTimestamp pgtype.Timestamptz `db:"request_timestamp" json:"request_timestamp"`
	StartedAt        pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt      pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	DurationMs       int64              `db:"duration_ms" json:"duration_ms"`
	ResponseStatus   *int32             `db:"response_status" json:"response_status"`
	ResponseHeaders  []byte             `db:"response_headers" json:"response_headers"`
	ResponseBody     *string            `db:"response_body" json:"response_body"`
	ErrorMessage     *string            `db:"error_message" json:"error_message"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WebhookEndpoint struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	TeamID              uuid.UUID          `db:"team_id" json:"team_id"`
	Url                 string             `db:"url" json:"url"`
	SigningSecret       []byte             `db:"signing_secret" json:"signing_secret"`
	Enabled             bool               `db:"enabled" json:"enabled"`
	SubscribedEvents    []string           `db:"subscribed_events" json:"subscribed_events"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt          pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	ConsecutiveFailures int32              `db:"consecutive_failures" json:"consecutive_failures"`
	LastFailureAt       pgtype.Timestamptz `db:"last_failure_at" json:"last_failure_at"`
	DisabledReason      *string            `db:"disabled_reason" json:"disabled_reason"`
}

type WebhookEvent struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TeamID     uuid.UUID          `db:"team_id" json:"team_id"`
	EventType  string             `db:"event_type" json:"event_type"`
	ObjectType string             `db:"object_type" json:"object_type"`
	ObjectID   *uuid.UUID         `db:"object_id" json:"object_id"`
	Payload    []byte             `db:"payload" json:"payload"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
