// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sender_ids.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSenderID = `-- name: CreateSenderID :one
INSERT INTO sender_ids (
    team_id,
    name,
    country_code,
    purpose,
    provider,
    created_by
)
SELECT
    team.id,
    $1,
    $2,
    $3,
    $4,
    $5
FROM teams AS team
WHERE team.id = $6
  AND team.status = 'active'
RETURNING id, team_id, name, country_code, purpose, status, provider, rejection_reason, approved_at, rejected_at, suspended_at, created_by, created_at, updated_at
`

type CreateSenderIDParams struct {
	Name        string     `db:"name" json:"name"`
	CountryCode string     `db:"country_code" json:"country_code"`
	Purpose     string     `db:"purpose" json:"purpose"`
	Provider    *string    `db:"provider" json:"provider"`
	CreatedBy   *uuid.UUID `db:"created_by" json:"created_by"`
	TeamID      uuid.UUID  `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateSenderID(ctx context.Context, arg CreateSenderIDParams) (SenderID, error) {
	row := q.db.QueryRow(ctx, createSenderID,
		arg.Name,
		arg.CountryCode,
		arg.Purpose,
		arg.Provider,
		arg.CreatedBy,
		arg.TeamID,
	)
	var i SenderID
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.CountryCode,
		&i.Purpose,
		&i.Status,
		&i.Provider,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.RejectedAt,
		&i.SuspendedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSenderID = `-- name: DeleteSenderID :one
DELETE FROM sender_ids AS sender
USING teams AS team
WHERE sender.id = $1
  AND sender.team_id = $2
  AND team.id = sender.team_id
  AND team.status = 'active'
RETURNING sender.id, sender.team_id, sender.name, sender.country_code, sender.purpose, sender.status, sender.provider, sender.rejection_reason, sender.approved_at, sender.rejected_at, sender.suspended_at, sender.created_by, sender.created_at, sender.updated_at
`

type DeleteSenderIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteSenderID(ctx context.Context, arg DeleteSenderIDParams) (SenderID, error) {
	row := q.db.QueryRow(ctx, deleteSenderID, arg.ID, arg.TeamID)
	var i SenderID
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.CountryCode,
		&i.Purpose,
		&i.Status,
		&i.Provider,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.RejectedAt,
		&i.SuspendedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSenderID = `-- name: GetSenderID :one
SELECT sender.id, sender.team_id, sender.name, sender.country_code, sender.purpose, sender.status, sender.provider, sender.rejection_reason, sender.approved_at, sender.rejected_at, sender.suspended_at, sender.created_by, sender.created_at, sender.updated_at
FROM sender_ids AS sender
JOIN teams AS team ON team.id = sender.team_id
WHERE sender.id = $1
  AND sender.team_id = $2
  AND team.status = 'active'
`

type GetSenderIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetSenderID(ctx context.Context, arg GetSenderIDParams) (SenderID, error) {
	row := q.db.QueryRow(ctx, getSenderID, arg.ID, arg.TeamID)
	var i SenderID
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.CountryCode,
		&i.Purpose,
		&i.Status,
		&i.Provider,
		&i.RejectionReason,
		&i.ApprovedAt,
		&i.RejectedAt,
		&i.SuspendedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSenderIDs = `-- name: ListSenderIDs :many
SELECT sender.id, sender.team_id, sender.name, sender.country_code, sender.purpose, sender.status, sender.provider, sender.rejection_reason, sender.approved_at, sender.rejected_at, sender.suspended_at, sender.created_by, sender.created_at, sender.updated_at
FROM sender_ids AS sender
JOIN teams AS team ON team.id = sender.team_id
WHERE sender.team_id = $1
  AND team.status = 'active'
ORDER BY sender.created_at DESC
`

type ListSenderIDsParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ListSenderIDs(ctx context.Context, arg ListSenderIDsParams) ([]SenderID, error) {
	rows, err := q.db.Query(ctx, listSenderIDs, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SenderID{}
	for rows.Next() {
		var i SenderID
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.CountryCode,
			&i.Purpose,
			&i.Status,
			&i.Provider,
			&i.RejectionReason,
			&i.ApprovedAt,
			&i.RejectedAt,
			&i.SuspendedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
