// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sender_domains.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimSenderDomainsForReconciliation = `-- name: ClaimSenderDomainsForReconciliation :many
WITH candidates AS (
    SELECT id
    FROM sender_domains
    WHERE sender_domains.status IN ('pending', 'verified')
      AND sender_domains.disabled_at IS NULL
      AND sender_domains.next_check_at <= now()
      AND (sender_domains.reconcile_locked_at IS NULL OR sender_domains.reconcile_locked_at < $2)
    ORDER BY sender_domains.next_check_at, sender_domains.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT $3
)
UPDATE sender_domains AS domain
SET reconcile_locked_at = now(),
    reconcile_locked_by = $1,
    verification_attempts = domain.verification_attempts + 1,
    updated_at = now()
FROM candidates
WHERE domain.id = candidates.id
RETURNING domain.id, domain.team_id, domain.domain, domain.provider, domain.provider_region, domain.status, domain.verification_records, domain.failure_reason, domain.last_checked_at, domain.next_check_at, domain.verification_attempts, domain.reconcile_locked_at, domain.reconcile_locked_by, domain.health_status, domain.consecutive_health_failures, domain.last_health_checked_at, domain.last_health_failure_at, domain.verified_at, domain.disabled_at, domain.created_by, domain.created_at, domain.updated_at
`

type ClaimSenderDomainsForReconciliationParams struct {
	WorkerID    *string            `db:"worker_id" json:"worker_id"`
	StaleBefore pgtype.Timestamptz `db:"stale_before" json:"stale_before"`
	BatchSize   int32              `db:"batch_size" json:"batch_size"`
}

func (q *Queries) ClaimSenderDomainsForReconciliation(ctx context.Context, arg ClaimSenderDomainsForReconciliationParams) ([]SenderDomain, error) {
	rows, err := q.db.Query(ctx, claimSenderDomainsForReconciliation, arg.WorkerID, arg.StaleBefore, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SenderDomain{}
	for rows.Next() {
		var i SenderDomain
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Domain,
			&i.Provider,
			&i.ProviderRegion,
			&i.Status,
			&i.VerificationRecords,
			&i.FailureReason,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.VerificationAttempts,
			&i.ReconcileLockedAt,
			&i.ReconcileLockedBy,
			&i.HealthStatus,
			&i.ConsecutiveHealthFailures,
			&i.LastHealthCheckedAt,
			&i.LastHealthFailureAt,
			&i.VerifiedAt,
			&i.DisabledAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeSenderDomainHealthCheck = `-- name: CompleteSenderDomainHealthCheck :one
UPDATE sender_domains
SET health_status = 'healthy',
    consecutive_health_failures = 0,
    failure_reason = NULL,
    last_checked_at = now(),
    last_health_checked_at = now(),
    next_check_at = $1,
    reconcile_locked_at = NULL,
    reconcile_locked_by = NULL,
    updated_at = now()
WHERE id = $2
  AND status = 'verified'
  AND reconcile_locked_by = $3
RETURNING id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, next_check_at, verification_attempts, reconcile_locked_at, reconcile_locked_by, health_status, consecutive_health_failures, last_health_checked_at, last_health_failure_at, verified_at, disabled_at, created_by, created_at, updated_at
`

type CompleteSenderDomainHealthCheckParams struct {
	NextCheckAt pgtype.Timestamptz `db:"next_check_at" json:"next_check_at"`
	ID          uuid.UUID          `db:"id" json:"id"`
	WorkerID    *string            `db:"worker_id" json:"worker_id"`
}

func (q *Queries) CompleteSenderDomainHealthCheck(ctx context.Context, arg CompleteSenderDomainHealthCheckParams) (SenderDomain, error) {
	row := q.db.QueryRow(ctx, completeSenderDomainHealthCheck, arg.NextCheckAt, arg.ID, arg.WorkerID)
	var i SenderDomain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Domain,
		&i.Provider,
		&i.ProviderRegion,
		&i.Status,
		&i.VerificationRecords,
		&i.FailureReason,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.VerificationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeSenderDomainReconciliation = `-- name: CompleteSenderDomainReconciliation :one
UPDATE sender_domains
SET status = $1,
    verification_records = $2,
    failure_reason = NULL,
    last_checked_at = now(),
    health_status = CASE WHEN $1 = 'verified' THEN 'healthy' ELSE health_status END,
    consecutive_health_failures = CASE WHEN $1 = 'verified' THEN 0 ELSE consecutive_health_failures END,
    last_health_checked_at = CASE WHEN $1 = 'verified' THEN now() ELSE last_health_checked_at END,
    next_check_at = $3,
    verified_at = CASE WHEN $1 = 'verified' THEN COALESCE(verified_at, now()) ELSE verified_at END,
    reconcile_locked_at = NULL,
    reconcile_locked_by = NULL,
    updated_at = now()
WHERE id = $4
  AND reconcile_locked_by = $5
RETURNING id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, next_check_at, verification_attempts, reconcile_locked_at, reconcile_locked_by, health_status, consecutive_health_failures, last_health_checked_at, last_health_failure_at, verified_at, disabled_at, created_by, created_at, updated_at
`

type CompleteSenderDomainReconciliationParams struct {
	Status              string             `db:"status" json:"status"`
	VerificationRecords []byte             `db:"verification_records" json:"verification_records"`
	NextCheckAt         pgtype.Timestamptz `db:"next_check_at" json:"next_check_at"`
	ID                  uuid.UUID          `db:"id" json:"id"`
	WorkerID            *string            `db:"worker_id" json:"worker_id"`
}

func (q *Queries) CompleteSenderDomainReconciliation(ctx context.Context, arg CompleteSenderDomainReconciliationParams) (SenderDomain, error) {
	row := q.db.QueryRow(ctx, completeSenderDomainReconciliation,
		arg.Status,
		arg.VerificationRecords,
		arg.NextCheckAt,
		arg.ID,
		arg.WorkerID,
	)
	var i SenderDomain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Domain,
		&i.Provider,
		&i.ProviderRegion,
		&i.Status,
		&i.VerificationRecords,
		&i.FailureReason,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.VerificationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSenderDomain = `-- name: CreateSenderDomain :one
INSERT INTO sender_domains (
    team_id,
    domain,
    provider,
    provider_region,
    verification_records,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, next_check_at, verification_attempts, reconcile_locked_at, reconcile_locked_by, health_status, consecutive_health_failures, last_health_checked_at, last_health_failure_at, verified_at, disabled_at, created_by, created_at, updated_at
`

type CreateSenderDomainParams struct {
	TeamID              uuid.UUID  `db:"team_id" json:"team_id"`
	Domain              string     `db:"domain" json:"domain"`
	Provider            string     `db:"provider" json:"provider"`
	ProviderRegion      string     `db:"provider_region" json:"provider_region"`
	VerificationRecords []byte     `db:"verification_records" json:"verification_records"`
	CreatedBy           *uuid.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateSenderDomain(ctx context.Context, arg CreateSenderDomainParams) (SenderDomain, error) {
	row := q.db.QueryRow(ctx, createSenderDomain,
		arg.TeamID,
		arg.Domain,
		arg.Provider,
		arg.ProviderRegion,
		arg.VerificationRecords,
		arg.CreatedBy,
	)
	var i SenderDomain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Domain,
		&i.Provider,
		&i.ProviderRegion,
		&i.Status,
		&i.VerificationRecords,
		&i.FailureReason,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.VerificationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSenderDomain = `-- name: DeleteSenderDomain :one
DELETE FROM sender_domains
WHERE id = $1
  AND team_id = $2
RETURNING id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, next_check_at, verification_attempts, reconcile_locked_at, reconcile_locked_by, health_status, consecutive_health_failures, last_health_checked_at, last_health_failure_at, verified_at, disabled_at, created_by, created_at, updated_at
`

type DeleteSenderDomainParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteSenderDomain(ctx context.Context, arg DeleteSenderDomainParams) (SenderDomain, error) {
	row := q.db.QueryRow(ctx, deleteSenderDomain, arg.ID, arg.TeamID)
	var i SenderDomain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Domain,
		&i.Provider,
		&i.ProviderRegion,
		&i.Status,
		&i.VerificationRecords,
		&i.FailureReason,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.VerificationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSenderDomain = `-- name: GetSenderDomain :one
SELECT id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, next_check_at, verification_attempts, reconcile_locked_at, reconcile_locked_by, health_status, consecutive_health_failures, last_health_checked_at, last_health_failure_at, verified_at, disabled_at, created_by, created_at, updated_at
FROM sender_domains
WHERE id = $1
  AND team_id = $2
`

type GetSenderDomainParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetSenderDomain(ctx context.Context, arg GetSenderDomainParams) (SenderDomain, error) {
	row := q.db.QueryRow(ctx, getSenderDomain, arg.ID, arg.TeamID)
	var i SenderDomain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Domain,
		&i.Provider,
		&i.ProviderRegion,
		&i.Status,
		&i.VerificationRecords,
		&i.FailureReason,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.VerificationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSenderDomainByDomain = `-- name: GetSenderDomainByDomain :one
SELECT id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, next_check_at, verification_attempts, reconcile_locked_at, reconcile_locked_by, health_status, consecutive_health_failures, last_health_checked_at, last_health_failure_at, verified_at, disabled_at, created_by, created_at, updated_at
FROM sender_domains
WHERE team_id = $1
  AND domain = $2
`

type GetSenderDomainByDomainParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Domain string    `db:"domain" json:"domain"`
}

func (q *Queries) GetSenderDomainByDomain(ctx context.Context, arg GetSenderDomainByDomainParams) (SenderDomain, error) {
	row := q.db.QueryRow(ctx, getSenderDomainByDomain, arg.TeamID, arg.Domain)
	var i SenderDomain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Domain,
		&i.Provider,
		&i.ProviderRegion,
		&i.Status,
		&i.VerificationRecords,
		&i.FailureReason,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.VerificationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSenderDomains = `-- name: ListSenderDomains :many
SELECT id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, next_check_at, verification_attempts, reconcile_locked_at, reconcile_locked_by, health_status, consecutive_health_failures, last_health_checked_at, last_health_failure_at, verified_at, disabled_at, created_by, created_at, updated_at
FROM sender_domains
WHERE team_id = $1
ORDER BY created_at DESC
`

type ListSenderDomainsParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ListSenderDomains(ctx context.Context, arg ListSenderDomainsParams) ([]SenderDomain, error) {
	rows, err := q.db.Query(ctx, listSenderDomains, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SenderDomain{}
	for rows.Next() {
		var i SenderDomain
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Domain,
			&i.Provider,
			&i.ProviderRegion,
			&i.Status,
			&i.VerificationRecords,
			&i.FailureReason,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.VerificationAttempts,
			&i.ReconcileLockedAt,
			&i.ReconcileLockedBy,
			&i.HealthStatus,
			&i.ConsecutiveHealthFailures,
			&i.LastHealthCheckedAt,
			&i.LastHealthFailureAt,
			&i.VerifiedAt,
			&i.DisabledAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSenderDomainHealthFailure = `-- name: RecordSenderDomainHealthFailure :one
UPDATE sender_domains
SET health_status = CASE
        WHEN consecutive_health_failures + 1 >= $1 THEN 'degraded'
        ELSE health_status
    END,
    consecutive_health_failures = consecutive_health_failures + 1,
    failure_reason = $2,
    last_checked_at = now(),
    last_health_checked_at = now(),
    last_health_failure_at = now(),
    next_check_at = $3,
    reconcile_locked_at = NULL,
    reconcile_locked_by = NULL,
    updated_at = now()
WHERE id = $4
  AND status = 'verified'
  AND reconcile_locked_by = $5
RETURNING id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, next_check_at, verification_attempts, reconcile_locked_at, reconcile_locked_by, health_status, consecutive_health_failures, last_health_checked_at, last_health_failure_at, verified_at, disabled_at, created_by, created_at, updated_at
`

type RecordSenderDomainHealthFailureParams struct {
	FailureThreshold int32              `db:"failure_threshold" json:"failure_threshold"`
	FailureReason    *string            `db:"failure_reason" json:"failure_reason"`
	NextCheckAt      pgtype.Timestamptz `db:"next_check_at" json:"next_check_at"`
	ID               uuid.UUID          `db:"id" json:"id"`
	WorkerID         *string            `db:"worker_id" json:"worker_id"`
}

func (q *Queries) RecordSenderDomainHealthFailure(ctx context.Context, arg RecordSenderDomainHealthFailureParams) (SenderDomain, error) {
	row := q.db.QueryRow(ctx, recordSenderDomainHealthFailure,
		arg.FailureThreshold,
		arg.FailureReason,
		arg.NextCheckAt,
		arg.ID,
		arg.WorkerID,
	)
	var i SenderDomain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Domain,
		&i.Provider,
		&i.ProviderRegion,
		&i.Status,
		&i.VerificationRecords,
		&i.FailureReason,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.VerificationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordSenderDomainReconciliationFailure = `-- name: RecordSenderDomainReconciliationFailure :one
UPDATE sender_domains
SET failure_reason = $1,
    last_checked_at = now(),
    next_check_at = $2,
    reconcile_locked_at = NULL,
    reconcile_locked_by = NULL,
    updated_at = now()
WHERE id = $3
  AND reconcile_locked_by = $4
RETURNING id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, next_check_at, verification_attempts, reconcile_locked_at, reconcile_locked_by, health_status, consecutive_health_failures, last_health_checked_at, last_health_failure_at, verified_at, disabled_at, created_by, created_at, updated_at
`

type RecordSenderDomainReconciliationFailureParams struct {
	FailureReason *string            `db:"failure_reason" json:"failure_reason"`
	NextCheckAt   pgtype.Timestamptz `db:"next_check_at" json:"next_check_at"`
	ID            uuid.UUID          `db:"id" json:"id"`
	WorkerID      *string            `db:"worker_id" json:"worker_id"`
}

func (q *Queries) RecordSenderDomainReconciliationFailure(ctx context.Context, arg RecordSenderDomainReconciliationFailureParams) (SenderDomain, error) {
	row := q.db.QueryRow(ctx, recordSenderDomainReconciliationFailure,
		arg.FailureReason,
		arg.NextCheckAt,
		arg.ID,
		arg.WorkerID,
	)
	var i SenderDomain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Domain,
		&i.Provider,
		&i.ProviderRegion,
		&i.Status,
		&i.VerificationRecords,
		&i.FailureReason,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.VerificationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSenderDomainVerification = `-- name: UpdateSenderDomainVerification :one
UPDATE sender_domains
SET status = $1,
    verification_records = $2,
    failure_reason = $3,
    last_checked_at = now(),
    health_status = CASE WHEN $1 = 'verified' THEN 'healthy' ELSE health_status END,
    consecutive_health_failures = CASE WHEN $1 = 'verified' THEN 0 ELSE consecutive_health_failures END,
    last_health_checked_at = CASE WHEN $1 = 'verified' THEN now() ELSE last_health_checked_at END,
    verified_at = CASE WHEN $1 = 'verified' THEN now() ELSE verified_at END,
    updated_at = now()
WHERE id = $4
  AND team_id = $5
RETURNING id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, next_check_at, verification_attempts, reconcile_locked_at, reconcile_locked_by, health_status, consecutive_health_failures, last_health_checked_at, last_health_failure_at, verified_at, disabled_at, created_by, created_at, updated_at
`

type UpdateSenderDomainVerificationParams struct {
	Status              string    `db:"status" json:"status"`
	VerificationRecords []byte    `db:"verification_records" json:"verification_records"`
	FailureReason       *string   `db:"failure_reason" json:"failure_reason"`
	ID                  uuid.UUID `db:"id" json:"id"`
	TeamID              uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateSenderDomainVerification(ctx context.Context, arg UpdateSenderDomainVerificationParams) (SenderDomain, error) {
	row := q.db.QueryRow(ctx, updateSenderDomainVerification,
		arg.Status,
		arg.VerificationRecords,
		arg.FailureReason,
		arg.ID,
		arg.TeamID,
	)
	var i SenderDomain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Domain,
		&i.Provider,
		&i.ProviderRegion,
		&i.Status,
		&i.VerificationRecords,
		&i.FailureReason,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.VerificationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
