// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sms_messages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSMSMessage = `-- name: CreateSMSMessage :one
INSERT INTO sms_messages (
    team_id,
    sender_id,
    to_number,
    from_name,
    body,
    status,
    segments,
    metadata,
    tags,
    scheduled_at,
    destination_country
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, team_id, sender_id, to_number, from_name, body, status, provider_id, provider_message_id, segments, error_message, metadata, tags, scheduled_at, submitted_at, delivered_at, created_at, updated_at, destination_country
`

type CreateSMSMessageParams struct {
	TeamID             uuid.UUID          `db:"team_id" json:"team_id"`
	SenderID           *uuid.UUID         `db:"sender_id" json:"sender_id"`
	ToNumber           string             `db:"to_number" json:"to_number"`
	FromName           string             `db:"from_name" json:"from_name"`
	Body               string             `db:"body" json:"body"`
	Status             string             `db:"status" json:"status"`
	Segments           int32              `db:"segments" json:"segments"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
	Tags               []byte             `db:"tags" json:"tags"`
	ScheduledAt        pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	DestinationCountry string             `db:"destination_country" json:"destination_country"`
}

func (q *Queries) CreateSMSMessage(ctx context.Context, arg CreateSMSMessageParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, createSMSMessage,
		arg.TeamID,
		arg.SenderID,
		arg.ToNumber,
		arg.FromName,
		arg.Body,
		arg.Status,
		arg.Segments,
		arg.Metadata,
		arg.Tags,
		arg.ScheduledAt,
		arg.DestinationCountry,
	)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SenderID,
		&i.ToNumber,
		&i.FromName,
		&i.Body,
		&i.Status,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.Segments,
		&i.ErrorMessage,
		&i.Metadata,
		&i.Tags,
		&i.ScheduledAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
	)
	return i, err
}

const findApprovedSMSSender = `-- name: FindApprovedSMSSender :one
SELECT id
FROM sender_ids
WHERE team_id = $1
  AND lower(name) = lower($2)
  AND status = 'approved'
ORDER BY created_at DESC
LIMIT 1
`

type FindApprovedSMSSenderParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Name   string    `db:"name" json:"name"`
}

func (q *Queries) FindApprovedSMSSender(ctx context.Context, arg FindApprovedSMSSenderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findApprovedSMSSender, arg.TeamID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSMSMessage = `-- name: GetSMSMessage :one
SELECT id, team_id, sender_id, to_number, from_name, body, status, provider_id, provider_message_id, segments, error_message, metadata, tags, scheduled_at, submitted_at, delivered_at, created_at, updated_at, destination_country
FROM sms_messages
WHERE id = $1
  AND team_id = $2
`

type GetSMSMessageParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetSMSMessage(ctx context.Context, arg GetSMSMessageParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, getSMSMessage, arg.ID, arg.TeamID)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SenderID,
		&i.ToNumber,
		&i.FromName,
		&i.Body,
		&i.Status,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.Segments,
		&i.ErrorMessage,
		&i.Metadata,
		&i.Tags,
		&i.ScheduledAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
	)
	return i, err
}

const listSMSMessages = `-- name: ListSMSMessages :many
SELECT id, team_id, sender_id, to_number, from_name, body, status, provider_id, provider_message_id, segments, error_message, metadata, tags, scheduled_at, submitted_at, delivered_at, created_at, updated_at, destination_country
FROM sms_messages
WHERE team_id = $1
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type ListSMSMessagesParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListSMSMessages(ctx context.Context, arg ListSMSMessagesParams) ([]SmsMessage, error) {
	rows, err := q.db.Query(ctx, listSMSMessages, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmsMessage{}
	for rows.Next() {
		var i SmsMessage
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.SenderID,
			&i.ToNumber,
			&i.FromName,
			&i.Body,
			&i.Status,
			&i.ProviderID,
			&i.ProviderMessageID,
			&i.Segments,
			&i.ErrorMessage,
			&i.Metadata,
			&i.Tags,
			&i.ScheduledAt,
			&i.SubmittedAt,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DestinationCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSMSMessageDeliveryUnknown = `-- name: MarkSMSMessageDeliveryUnknown :one
UPDATE sms_messages
SET status = 'unknown',
    error_message = $1,
    updated_at = now()
WHERE id = $2
  AND team_id = $3
  AND status = 'processing'
  AND provider_message_id IS NULL
RETURNING id, team_id, sender_id, to_number, from_name, body, status, provider_id, provider_message_id, segments, error_message, metadata, tags, scheduled_at, submitted_at, delivered_at, created_at, updated_at, destination_country
`

type MarkSMSMessageDeliveryUnknownParams struct {
	ErrorMessage *string   `db:"error_message" json:"error_message"`
	ID           uuid.UUID `db:"id" json:"id"`
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkSMSMessageDeliveryUnknown(ctx context.Context, arg MarkSMSMessageDeliveryUnknownParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, markSMSMessageDeliveryUnknown, arg.ErrorMessage, arg.ID, arg.TeamID)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SenderID,
		&i.ToNumber,
		&i.FromName,
		&i.Body,
		&i.Status,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.Segments,
		&i.ErrorMessage,
		&i.Metadata,
		&i.Tags,
		&i.ScheduledAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
	)
	return i, err
}

const markSMSMessageFailed = `-- name: MarkSMSMessageFailed :one
UPDATE sms_messages
SET status = 'failed',
    error_message = $1,
    updated_at = now()
WHERE id = $2
  AND team_id = $3
RETURNING id, team_id, sender_id, to_number, from_name, body, status, provider_id, provider_message_id, segments, error_message, metadata, tags, scheduled_at, submitted_at, delivered_at, created_at, updated_at, destination_country
`

type MarkSMSMessageFailedParams struct {
	ErrorMessage *string   `db:"error_message" json:"error_message"`
	ID           uuid.UUID `db:"id" json:"id"`
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkSMSMessageFailed(ctx context.Context, arg MarkSMSMessageFailedParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, markSMSMessageFailed, arg.ErrorMessage, arg.ID, arg.TeamID)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SenderID,
		&i.ToNumber,
		&i.FromName,
		&i.Body,
		&i.Status,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.Segments,
		&i.ErrorMessage,
		&i.Metadata,
		&i.Tags,
		&i.ScheduledAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
	)
	return i, err
}

const markSMSMessageProcessing = `-- name: MarkSMSMessageProcessing :one
UPDATE sms_messages
SET status = 'processing',
    error_message = NULL,
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status = 'queued'
  AND provider_message_id IS NULL
RETURNING id, team_id, sender_id, to_number, from_name, body, status, provider_id, provider_message_id, segments, error_message, metadata, tags, scheduled_at, submitted_at, delivered_at, created_at, updated_at, destination_country
`

type MarkSMSMessageProcessingParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkSMSMessageProcessing(ctx context.Context, arg MarkSMSMessageProcessingParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, markSMSMessageProcessing, arg.ID, arg.TeamID)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SenderID,
		&i.ToNumber,
		&i.FromName,
		&i.Body,
		&i.Status,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.Segments,
		&i.ErrorMessage,
		&i.Metadata,
		&i.Tags,
		&i.ScheduledAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
	)
	return i, err
}

const markSMSMessageSubmitted = `-- name: MarkSMSMessageSubmitted :one
UPDATE sms_messages
SET provider_id = $1,
    provider_message_id = $2,
    status = $3,
    error_message = NULL,
    submitted_at = COALESCE(submitted_at, now()),
    updated_at = now()
WHERE id = $4
  AND team_id = $5
RETURNING id, team_id, sender_id, to_number, from_name, body, status, provider_id, provider_message_id, segments, error_message, metadata, tags, scheduled_at, submitted_at, delivered_at, created_at, updated_at, destination_country
`

type MarkSMSMessageSubmittedParams struct {
	ProviderID        *string   `db:"provider_id" json:"provider_id"`
	ProviderMessageID *string   `db:"provider_message_id" json:"provider_message_id"`
	Status            string    `db:"status" json:"status"`
	ID                uuid.UUID `db:"id" json:"id"`
	TeamID            uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkSMSMessageSubmitted(ctx context.Context, arg MarkSMSMessageSubmittedParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, markSMSMessageSubmitted,
		arg.ProviderID,
		arg.ProviderMessageID,
		arg.Status,
		arg.ID,
		arg.TeamID,
	)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SenderID,
		&i.ToNumber,
		&i.FromName,
		&i.Body,
		&i.Status,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.Segments,
		&i.ErrorMessage,
		&i.Metadata,
		&i.Tags,
		&i.ScheduledAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
	)
	return i, err
}

const updateSMSMessageStatus = `-- name: UpdateSMSMessageStatus :one
UPDATE sms_messages
SET status = $1,
    delivered_at = CASE
        WHEN $1 = 'delivered'
            THEN COALESCE(delivered_at, now())
        ELSE delivered_at
    END,
    updated_at = now()
WHERE id = $2
  AND team_id = $3
  AND status <> $1
  AND status NOT IN ('delivered', 'undelivered', 'rejected', 'failed', 'expired', 'unknown', 'canceled')
  AND (
      $1 IN ('delivered', 'undelivered', 'rejected', 'failed', 'expired')
      OR CASE status
          WHEN 'queued' THEN 0
          WHEN 'processing' THEN 1
          WHEN 'submitted' THEN 2
          WHEN 'sent' THEN 3
          ELSE 4
      END < CASE $1
          WHEN 'queued' THEN 0
          WHEN 'processing' THEN 1
          WHEN 'submitted' THEN 2
          WHEN 'sent' THEN 3
          ELSE -1
      END
  )
RETURNING id, team_id, sender_id, to_number, from_name, body, status, provider_id, provider_message_id, segments, error_message, metadata, tags, scheduled_at, submitted_at, delivered_at, created_at, updated_at, destination_country
`

type UpdateSMSMessageStatusParams struct {
	Status string    `db:"status" json:"status"`
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateSMSMessageStatus(ctx context.Context, arg UpdateSMSMessageStatusParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, updateSMSMessageStatus, arg.Status, arg.ID, arg.TeamID)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SenderID,
		&i.ToNumber,
		&i.FromName,
		&i.Body,
		&i.Status,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.Segments,
		&i.ErrorMessage,
		&i.Metadata,
		&i.Tags,
		&i.ScheduledAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DestinationCountry,
	)
	return i, err
}
