// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suppressions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSuppression = `-- name: CreateSuppression :one
INSERT INTO suppressions (
    team_id,
    email,
    origin,
    source_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, team_id, email, origin, source_id, created_at
`

type CreateSuppressionParams struct {
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
	Email    string    `db:"email" json:"email"`
	Origin   string    `db:"origin" json:"origin"`
	SourceID *string   `db:"source_id" json:"source_id"`
}

func (q *Queries) CreateSuppression(ctx context.Context, arg CreateSuppressionParams) (Suppression, error) {
	row := q.db.QueryRow(ctx, createSuppression,
		arg.TeamID,
		arg.Email,
		arg.Origin,
		arg.SourceID,
	)
	var i Suppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSuppressionByEmail = `-- name: DeleteSuppressionByEmail :one
DELETE FROM suppressions
WHERE team_id = $1
  AND lower(email) = lower($2)
RETURNING id, team_id, email, origin, source_id, created_at
`

type DeleteSuppressionByEmailParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Email  string    `db:"email" json:"email"`
}

func (q *Queries) DeleteSuppressionByEmail(ctx context.Context, arg DeleteSuppressionByEmailParams) (Suppression, error) {
	row := q.db.QueryRow(ctx, deleteSuppressionByEmail, arg.TeamID, arg.Email)
	var i Suppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSuppressionByID = `-- name: DeleteSuppressionByID :one
DELETE FROM suppressions
WHERE id = $1
  AND team_id = $2
RETURNING id, team_id, email, origin, source_id, created_at
`

type DeleteSuppressionByIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteSuppressionByID(ctx context.Context, arg DeleteSuppressionByIDParams) (Suppression, error) {
	row := q.db.QueryRow(ctx, deleteSuppressionByID, arg.ID, arg.TeamID)
	var i Suppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const getSuppressionByEmail = `-- name: GetSuppressionByEmail :one
SELECT id, team_id, email, origin, source_id, created_at
FROM suppressions
WHERE team_id = $1
  AND lower(email) = lower($2)
`

type GetSuppressionByEmailParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Email  string    `db:"email" json:"email"`
}

func (q *Queries) GetSuppressionByEmail(ctx context.Context, arg GetSuppressionByEmailParams) (Suppression, error) {
	row := q.db.QueryRow(ctx, getSuppressionByEmail, arg.TeamID, arg.Email)
	var i Suppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const getSuppressionByID = `-- name: GetSuppressionByID :one
SELECT id, team_id, email, origin, source_id, created_at
FROM suppressions
WHERE id = $1
  AND team_id = $2
`

type GetSuppressionByIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetSuppressionByID(ctx context.Context, arg GetSuppressionByIDParams) (Suppression, error) {
	row := q.db.QueryRow(ctx, getSuppressionByID, arg.ID, arg.TeamID)
	var i Suppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const listSuppressions = `-- name: ListSuppressions :many
SELECT id, team_id, email, origin, source_id, created_at
FROM suppressions
WHERE team_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListSuppressionsParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListSuppressions(ctx context.Context, arg ListSuppressionsParams) ([]Suppression, error) {
	rows, err := q.db.Query(ctx, listSuppressions, arg.TeamID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Suppression{}
	for rows.Next() {
		var i Suppression
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Origin,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
