// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suppressions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSuppression = `-- name: CreateSuppression :one
INSERT INTO suppressions (
    team_id,
    email,
    origin,
    source_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id,
          team_id,
          email,
          origin,
          source_id,
          created_at
`

type CreateSuppressionParams struct {
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
	Email    string    `db:"email" json:"email"`
	Origin   string    `db:"origin" json:"origin"`
	SourceID *string   `db:"source_id" json:"source_id"`
}

func (q *Queries) CreateSuppression(ctx context.Context, arg CreateSuppressionParams) (Suppression, error) {
	row := q.db.QueryRow(ctx, createSuppression,
		arg.TeamID,
		arg.Email,
		arg.Origin,
		arg.SourceID,
	)
	var i Suppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const createSuppressions = `-- name: CreateSuppressions :many
INSERT INTO suppressions (
    team_id,
    email,
    origin
)
SELECT $1,
       lower(batch_email.email),
       'manual'
FROM unnest($2::text[]) WITH ORDINALITY AS batch_email(email, position)
ORDER BY batch_email.position
RETURNING id,
          team_id,
          email,
          origin,
          source_id,
          created_at
`

type CreateSuppressionsParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Emails []string  `db:"emails" json:"emails"`
}

func (q *Queries) CreateSuppressions(ctx context.Context, arg CreateSuppressionsParams) ([]Suppression, error) {
	rows, err := q.db.Query(ctx, createSuppressions, arg.TeamID, arg.Emails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Suppression{}
	for rows.Next() {
		var i Suppression
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Origin,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSuppressionByEmail = `-- name: DeleteSuppressionByEmail :one
DELETE FROM suppressions
WHERE team_id = $1
  AND lower(email) = lower($2)
RETURNING id,
          team_id,
          email,
          origin,
          source_id,
          created_at
`

type DeleteSuppressionByEmailParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Email  string    `db:"email" json:"email"`
}

func (q *Queries) DeleteSuppressionByEmail(ctx context.Context, arg DeleteSuppressionByEmailParams) (Suppression, error) {
	row := q.db.QueryRow(ctx, deleteSuppressionByEmail, arg.TeamID, arg.Email)
	var i Suppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSuppressionByID = `-- name: DeleteSuppressionByID :one
DELETE FROM suppressions
WHERE id = $1
  AND team_id = $2
RETURNING id,
          team_id,
          email,
          origin,
          source_id,
          created_at
`

type DeleteSuppressionByIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteSuppressionByID(ctx context.Context, arg DeleteSuppressionByIDParams) (Suppression, error) {
	row := q.db.QueryRow(ctx, deleteSuppressionByID, arg.ID, arg.TeamID)
	var i Suppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSuppressionsByEmails = `-- name: DeleteSuppressionsByEmails :many
DELETE FROM suppressions
WHERE team_id = $1
  AND lower(email) = ANY($2::text[])
RETURNING id,
          team_id,
          email,
          origin,
          source_id,
          created_at
`

type DeleteSuppressionsByEmailsParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Emails []string  `db:"emails" json:"emails"`
}

func (q *Queries) DeleteSuppressionsByEmails(ctx context.Context, arg DeleteSuppressionsByEmailsParams) ([]Suppression, error) {
	rows, err := q.db.Query(ctx, deleteSuppressionsByEmails, arg.TeamID, arg.Emails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Suppression{}
	for rows.Next() {
		var i Suppression
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Origin,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSuppressionsByIDs = `-- name: DeleteSuppressionsByIDs :many
DELETE FROM suppressions
WHERE team_id = $1
  AND id = ANY($2::uuid[])
RETURNING id,
          team_id,
          email,
          origin,
          source_id,
          created_at
`

type DeleteSuppressionsByIDsParams struct {
	TeamID uuid.UUID   `db:"team_id" json:"team_id"`
	Ids    []uuid.UUID `db:"ids" json:"ids"`
}

func (q *Queries) DeleteSuppressionsByIDs(ctx context.Context, arg DeleteSuppressionsByIDsParams) ([]Suppression, error) {
	rows, err := q.db.Query(ctx, deleteSuppressionsByIDs, arg.TeamID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Suppression{}
	for rows.Next() {
		var i Suppression
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Origin,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuppressionByEmail = `-- name: GetSuppressionByEmail :one
SELECT s.id,
       s.team_id,
       s.email,
       s.origin,
       s.source_id,
       s.created_at
FROM suppressions AS s
WHERE s.team_id = $1
  AND lower(s.email) = lower($2)
`

type GetSuppressionByEmailParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Email  string    `db:"email" json:"email"`
}

func (q *Queries) GetSuppressionByEmail(ctx context.Context, arg GetSuppressionByEmailParams) (Suppression, error) {
	row := q.db.QueryRow(ctx, getSuppressionByEmail, arg.TeamID, arg.Email)
	var i Suppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const getSuppressionByID = `-- name: GetSuppressionByID :one
SELECT s.id,
       s.team_id,
       s.email,
       s.origin,
       s.source_id,
       s.created_at
FROM suppressions AS s
WHERE s.id = $1
  AND s.team_id = $2
`

type GetSuppressionByIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetSuppressionByID(ctx context.Context, arg GetSuppressionByIDParams) (Suppression, error) {
	row := q.db.QueryRow(ctx, getSuppressionByID, arg.ID, arg.TeamID)
	var i Suppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const listSuppressions = `-- name: ListSuppressions :many
SELECT s.id,
       s.team_id,
       s.email,
       s.origin,
       s.source_id,
       s.created_at
FROM suppressions AS s
WHERE s.team_id = $1
ORDER BY s.created_at DESC, s.id DESC
LIMIT $3
OFFSET $2
`

type ListSuppressionsParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListSuppressions(ctx context.Context, arg ListSuppressionsParams) ([]Suppression, error) {
	rows, err := q.db.Query(ctx, listSuppressions, arg.TeamID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Suppression{}
	for rows.Next() {
		var i Suppression
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Origin,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppressionsAfter = `-- name: ListSuppressionsAfter :many
SELECT s.id,
       s.team_id,
       s.email,
       s.origin,
       s.source_id,
       s.created_at
FROM suppressions AS s
WHERE s.team_id = $1
  AND ($2::text IS NULL OR s.origin = $2)
  AND (s.created_at, s.id) < (
      SELECT cursor_suppression.created_at, cursor_suppression.id
      FROM suppressions AS cursor_suppression
      WHERE cursor_suppression.id = $3
        AND cursor_suppression.team_id = $1
  )
ORDER BY s.created_at DESC, s.id DESC
LIMIT $4
`

type ListSuppressionsAfterParams struct {
	ScopeTeamID  uuid.UUID `db:"scope_team_id" json:"scope_team_id"`
	FilterOrigin *string   `db:"filter_origin" json:"filter_origin"`
	CursorID     uuid.UUID `db:"cursor_id" json:"cursor_id"`
	PageLimit    int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListSuppressionsAfter(ctx context.Context, arg ListSuppressionsAfterParams) ([]Suppression, error) {
	rows, err := q.db.Query(ctx, listSuppressionsAfter,
		arg.ScopeTeamID,
		arg.FilterOrigin,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Suppression{}
	for rows.Next() {
		var i Suppression
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Origin,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppressionsBefore = `-- name: ListSuppressionsBefore :many
SELECT s.id,
       s.team_id,
       s.email,
       s.origin,
       s.source_id,
       s.created_at
FROM suppressions AS s
WHERE s.team_id = $1
  AND ($2::text IS NULL OR s.origin = $2)
  AND (s.created_at, s.id) > (
      SELECT cursor_suppression.created_at, cursor_suppression.id
      FROM suppressions AS cursor_suppression
      WHERE cursor_suppression.id = $3
        AND cursor_suppression.team_id = $1
  )
ORDER BY s.created_at ASC, s.id ASC
LIMIT $4
`

type ListSuppressionsBeforeParams struct {
	ScopeTeamID  uuid.UUID `db:"scope_team_id" json:"scope_team_id"`
	FilterOrigin *string   `db:"filter_origin" json:"filter_origin"`
	CursorID     uuid.UUID `db:"cursor_id" json:"cursor_id"`
	PageLimit    int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListSuppressionsBefore(ctx context.Context, arg ListSuppressionsBeforeParams) ([]Suppression, error) {
	rows, err := q.db.Query(ctx, listSuppressionsBefore,
		arg.ScopeTeamID,
		arg.FilterOrigin,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Suppression{}
	for rows.Next() {
		var i Suppression
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Origin,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppressionsFiltered = `-- name: ListSuppressionsFiltered :many
SELECT s.id,
       s.team_id,
       s.email,
       s.origin,
       s.source_id,
       s.created_at
FROM suppressions AS s
WHERE s.team_id = $1
  AND ($2::text IS NULL OR s.origin = $2)
ORDER BY s.created_at DESC, s.id DESC
LIMIT $3
`

type ListSuppressionsFilteredParams struct {
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
	FilterOrigin *string   `db:"filter_origin" json:"filter_origin"`
	PageLimit    int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListSuppressionsFiltered(ctx context.Context, arg ListSuppressionsFilteredParams) ([]Suppression, error) {
	rows, err := q.db.Query(ctx, listSuppressionsFiltered, arg.TeamID, arg.FilterOrigin, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Suppression{}
	for rows.Next() {
		var i Suppression
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Origin,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suppressionCursorExists = `-- name: SuppressionCursorExists :one
SELECT EXISTS (
    SELECT 1
    FROM suppressions AS s
    WHERE s.id = $1
      AND s.team_id = $2
)
`

type SuppressionCursorExistsParams struct {
	CursorID uuid.UUID `db:"cursor_id" json:"cursor_id"`
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) SuppressionCursorExists(ctx context.Context, arg SuppressionCursorExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, suppressionCursorExists, arg.CursorID, arg.TeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
