// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_services.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createVerificationService = `-- name: CreateVerificationService :one
INSERT INTO verification_services (
    team_id,
    key,
    name,
    default_channel,
    code_length,
    ttl_seconds,
    max_attempts,
    resend_cooldown_seconds,
    max_resends,
    enabled,
    metadata
)
SELECT
    team.id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
FROM teams AS team
WHERE team.id = $11
  AND team.status = 'active'
RETURNING id, team_id, key, name, default_channel, code_length, ttl_seconds, max_attempts, resend_cooldown_seconds, max_resends, enabled, metadata, created_at, updated_at
`

type CreateVerificationServiceParams struct {
	Key                   string    `db:"key" json:"key"`
	Name                  string    `db:"name" json:"name"`
	DefaultChannel        string    `db:"default_channel" json:"default_channel"`
	CodeLength            int32     `db:"code_length" json:"code_length"`
	TtlSeconds            int32     `db:"ttl_seconds" json:"ttl_seconds"`
	MaxAttempts           int32     `db:"max_attempts" json:"max_attempts"`
	ResendCooldownSeconds int32     `db:"resend_cooldown_seconds" json:"resend_cooldown_seconds"`
	MaxResends            int32     `db:"max_resends" json:"max_resends"`
	Enabled               bool      `db:"enabled" json:"enabled"`
	Metadata              []byte    `db:"metadata" json:"metadata"`
	TeamID                uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateVerificationService(ctx context.Context, arg CreateVerificationServiceParams) (VerificationService, error) {
	row := q.db.QueryRow(ctx, createVerificationService,
		arg.Key,
		arg.Name,
		arg.DefaultChannel,
		arg.CodeLength,
		arg.TtlSeconds,
		arg.MaxAttempts,
		arg.ResendCooldownSeconds,
		arg.MaxResends,
		arg.Enabled,
		arg.Metadata,
		arg.TeamID,
	)
	var i VerificationService
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.Name,
		&i.DefaultChannel,
		&i.CodeLength,
		&i.TtlSeconds,
		&i.MaxAttempts,
		&i.ResendCooldownSeconds,
		&i.MaxResends,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerificationService = `-- name: GetVerificationService :one
SELECT service.id, service.team_id, service.key, service.name, service.default_channel, service.code_length, service.ttl_seconds, service.max_attempts, service.resend_cooldown_seconds, service.max_resends, service.enabled, service.metadata, service.created_at, service.updated_at
FROM verification_services AS service
JOIN teams AS team ON team.id = service.team_id
WHERE service.id = $1
  AND service.team_id = $2
  AND team.status = 'active'
`

type GetVerificationServiceParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetVerificationService(ctx context.Context, arg GetVerificationServiceParams) (VerificationService, error) {
	row := q.db.QueryRow(ctx, getVerificationService, arg.ID, arg.TeamID)
	var i VerificationService
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.Name,
		&i.DefaultChannel,
		&i.CodeLength,
		&i.TtlSeconds,
		&i.MaxAttempts,
		&i.ResendCooldownSeconds,
		&i.MaxResends,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerificationServiceByKey = `-- name: GetVerificationServiceByKey :one
SELECT service.id, service.team_id, service.key, service.name, service.default_channel, service.code_length, service.ttl_seconds, service.max_attempts, service.resend_cooldown_seconds, service.max_resends, service.enabled, service.metadata, service.created_at, service.updated_at
FROM verification_services AS service
JOIN teams AS team ON team.id = service.team_id
WHERE service.team_id = $1
  AND service.key = $2
  AND team.status = 'active'
`

type GetVerificationServiceByKeyParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Key    string    `db:"key" json:"key"`
}

func (q *Queries) GetVerificationServiceByKey(ctx context.Context, arg GetVerificationServiceByKeyParams) (VerificationService, error) {
	row := q.db.QueryRow(ctx, getVerificationServiceByKey, arg.TeamID, arg.Key)
	var i VerificationService
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.Name,
		&i.DefaultChannel,
		&i.CodeLength,
		&i.TtlSeconds,
		&i.MaxAttempts,
		&i.ResendCooldownSeconds,
		&i.MaxResends,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVerificationServices = `-- name: ListVerificationServices :many
SELECT service.id, service.team_id, service.key, service.name, service.default_channel, service.code_length, service.ttl_seconds, service.max_attempts, service.resend_cooldown_seconds, service.max_resends, service.enabled, service.metadata, service.created_at, service.updated_at
FROM verification_services AS service
JOIN teams AS team ON team.id = service.team_id
WHERE service.team_id = $1
  AND team.status = 'active'
ORDER BY service.created_at DESC, service.id DESC
LIMIT $3
OFFSET $2
`

type ListVerificationServicesParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListVerificationServices(ctx context.Context, arg ListVerificationServicesParams) ([]VerificationService, error) {
	rows, err := q.db.Query(ctx, listVerificationServices, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerificationService{}
	for rows.Next() {
		var i VerificationService
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Key,
			&i.Name,
			&i.DefaultChannel,
			&i.CodeLength,
			&i.TtlSeconds,
			&i.MaxAttempts,
			&i.ResendCooldownSeconds,
			&i.MaxResends,
			&i.Enabled,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVerificationServiceEnabled = `-- name: SetVerificationServiceEnabled :one
UPDATE verification_services AS service
SET enabled = $1,
    updated_at = now()
FROM teams AS team
WHERE service.id = $2
  AND service.team_id = $3
  AND team.id = service.team_id
  AND team.status = 'active'
RETURNING service.id, service.team_id, service.key, service.name, service.default_channel, service.code_length, service.ttl_seconds, service.max_attempts, service.resend_cooldown_seconds, service.max_resends, service.enabled, service.metadata, service.created_at, service.updated_at
`

type SetVerificationServiceEnabledParams struct {
	Enabled bool      `db:"enabled" json:"enabled"`
	ID      uuid.UUID `db:"id" json:"id"`
	TeamID  uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) SetVerificationServiceEnabled(ctx context.Context, arg SetVerificationServiceEnabledParams) (VerificationService, error) {
	row := q.db.QueryRow(ctx, setVerificationServiceEnabled, arg.Enabled, arg.ID, arg.TeamID)
	var i VerificationService
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.Name,
		&i.DefaultChannel,
		&i.CodeLength,
		&i.TtlSeconds,
		&i.MaxAttempts,
		&i.ResendCooldownSeconds,
		&i.MaxResends,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVerificationService = `-- name: UpdateVerificationService :one
UPDATE verification_services AS service
SET name = $1,
    default_channel = $2,
    code_length = $3,
    ttl_seconds = $4,
    max_attempts = $5,
    resend_cooldown_seconds = $6,
    max_resends = $7,
    metadata = $8,
    updated_at = now()
FROM teams AS team
WHERE service.id = $9
  AND service.team_id = $10
  AND team.id = service.team_id
  AND team.status = 'active'
RETURNING service.id, service.team_id, service.key, service.name, service.default_channel, service.code_length, service.ttl_seconds, service.max_attempts, service.resend_cooldown_seconds, service.max_resends, service.enabled, service.metadata, service.created_at, service.updated_at
`

type UpdateVerificationServiceParams struct {
	Name                  string    `db:"name" json:"name"`
	DefaultChannel        string    `db:"default_channel" json:"default_channel"`
	CodeLength            int32     `db:"code_length" json:"code_length"`
	TtlSeconds            int32     `db:"ttl_seconds" json:"ttl_seconds"`
	MaxAttempts           int32     `db:"max_attempts" json:"max_attempts"`
	ResendCooldownSeconds int32     `db:"resend_cooldown_seconds" json:"resend_cooldown_seconds"`
	MaxResends            int32     `db:"max_resends" json:"max_resends"`
	Metadata              []byte    `db:"metadata" json:"metadata"`
	ID                    uuid.UUID `db:"id" json:"id"`
	TeamID                uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateVerificationService(ctx context.Context, arg UpdateVerificationServiceParams) (VerificationService, error) {
	row := q.db.QueryRow(ctx, updateVerificationService,
		arg.Name,
		arg.DefaultChannel,
		arg.CodeLength,
		arg.TtlSeconds,
		arg.MaxAttempts,
		arg.ResendCooldownSeconds,
		arg.MaxResends,
		arg.Metadata,
		arg.ID,
		arg.TeamID,
	)
	var i VerificationService
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.Name,
		&i.DefaultChannel,
		&i.CodeLength,
		&i.TtlSeconds,
		&i.MaxAttempts,
		&i.ResendCooldownSeconds,
		&i.MaxResends,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
