// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verifications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveVerification = `-- name: ApproveVerification :one
UPDATE verifications
SET status = 'approved',
    approved_at = now(),
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status = 'pending'
  AND expires_at > now()
RETURNING id, team_id, service_id, channel, recipient, recipient_normalized, status, locale, metadata, attempt_count, resend_count, expires_at, approved_at, expired_at, canceled_at, failed_at, created_at, updated_at
`

type ApproveVerificationParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ApproveVerification(ctx context.Context, arg ApproveVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, approveVerification, arg.ID, arg.TeamID)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ServiceID,
		&i.Channel,
		&i.Recipient,
		&i.RecipientNormalized,
		&i.Status,
		&i.Locale,
		&i.Metadata,
		&i.AttemptCount,
		&i.ResendCount,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExpiredAt,
		&i.CanceledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelVerification = `-- name: CancelVerification :one
UPDATE verifications
SET status = 'canceled',
    canceled_at = now(),
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status = 'pending'
RETURNING id, team_id, service_id, channel, recipient, recipient_normalized, status, locale, metadata, attempt_count, resend_count, expires_at, approved_at, expired_at, canceled_at, failed_at, created_at, updated_at
`

type CancelVerificationParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) CancelVerification(ctx context.Context, arg CancelVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, cancelVerification, arg.ID, arg.TeamID)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ServiceID,
		&i.Channel,
		&i.Recipient,
		&i.RecipientNormalized,
		&i.Status,
		&i.Locale,
		&i.Metadata,
		&i.AttemptCount,
		&i.ResendCount,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExpiredAt,
		&i.CanceledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVerification = `-- name: CreateVerification :one
INSERT INTO verifications (
    team_id, service_id, channel, recipient, recipient_normalized,
    status, locale, metadata, expires_at
)
SELECT
    service.team_id, service.id, $1, $2,
    $3, 'pending', $4,
    $5, $6
FROM verification_services AS service
JOIN teams AS team ON team.id = service.team_id
WHERE service.id = $7
  AND service.team_id = $8
  AND service.enabled = true
  AND team.status = 'active'
RETURNING id, team_id, service_id, channel, recipient, recipient_normalized, status, locale, metadata, attempt_count, resend_count, expires_at, approved_at, expired_at, canceled_at, failed_at, created_at, updated_at
`

type CreateVerificationParams struct {
	Channel             string             `db:"channel" json:"channel"`
	Recipient           string             `db:"recipient" json:"recipient"`
	RecipientNormalized string             `db:"recipient_normalized" json:"recipient_normalized"`
	Locale              *string            `db:"locale" json:"locale"`
	Metadata            []byte             `db:"metadata" json:"metadata"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ServiceID           uuid.UUID          `db:"service_id" json:"service_id"`
	TeamID              uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, createVerification,
		arg.Channel,
		arg.Recipient,
		arg.RecipientNormalized,
		arg.Locale,
		arg.Metadata,
		arg.ExpiresAt,
		arg.ServiceID,
		arg.TeamID,
	)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ServiceID,
		&i.Channel,
		&i.Recipient,
		&i.RecipientNormalized,
		&i.Status,
		&i.Locale,
		&i.Metadata,
		&i.AttemptCount,
		&i.ResendCount,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExpiredAt,
		&i.CanceledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expirePendingVerifications = `-- name: ExpirePendingVerifications :many
UPDATE verifications
SET status = 'expired',
    expired_at = now(),
    updated_at = now()
WHERE status = 'pending'
  AND expires_at <= now()
RETURNING id, team_id, service_id, channel, recipient, recipient_normalized, status, locale, metadata, attempt_count, resend_count, expires_at, approved_at, expired_at, canceled_at, failed_at, created_at, updated_at
`

func (q *Queries) ExpirePendingVerifications(ctx context.Context) ([]Verification, error) {
	rows, err := q.db.Query(ctx, expirePendingVerifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Verification{}
	for rows.Next() {
		var i Verification
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ServiceID,
			&i.Channel,
			&i.Recipient,
			&i.RecipientNormalized,
			&i.Status,
			&i.Locale,
			&i.Metadata,
			&i.AttemptCount,
			&i.ResendCount,
			&i.ExpiresAt,
			&i.ApprovedAt,
			&i.ExpiredAt,
			&i.CanceledAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireVerification = `-- name: ExpireVerification :one
UPDATE verifications
SET status = 'expired',
    expired_at = now(),
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status = 'pending'
RETURNING id, team_id, service_id, channel, recipient, recipient_normalized, status, locale, metadata, attempt_count, resend_count, expires_at, approved_at, expired_at, canceled_at, failed_at, created_at, updated_at
`

type ExpireVerificationParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ExpireVerification(ctx context.Context, arg ExpireVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, expireVerification, arg.ID, arg.TeamID)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ServiceID,
		&i.Channel,
		&i.Recipient,
		&i.RecipientNormalized,
		&i.Status,
		&i.Locale,
		&i.Metadata,
		&i.AttemptCount,
		&i.ResendCount,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExpiredAt,
		&i.CanceledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerification = `-- name: GetVerification :one
SELECT verification.id, verification.team_id, verification.service_id, verification.channel, verification.recipient, verification.recipient_normalized, verification.status, verification.locale, verification.metadata, verification.attempt_count, verification.resend_count, verification.expires_at, verification.approved_at, verification.expired_at, verification.canceled_at, verification.failed_at, verification.created_at, verification.updated_at
FROM verifications AS verification
JOIN teams AS team ON team.id = verification.team_id
WHERE verification.id = $1
  AND verification.team_id = $2
  AND team.status = 'active'
`

type GetVerificationParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetVerification(ctx context.Context, arg GetVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, getVerification, arg.ID, arg.TeamID)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ServiceID,
		&i.Channel,
		&i.Recipient,
		&i.RecipientNormalized,
		&i.Status,
		&i.Locale,
		&i.Metadata,
		&i.AttemptCount,
		&i.ResendCount,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExpiredAt,
		&i.CanceledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerificationForUpdate = `-- name: GetVerificationForUpdate :one
SELECT id, team_id, service_id, channel, recipient, recipient_normalized, status, locale, metadata, attempt_count, resend_count, expires_at, approved_at, expired_at, canceled_at, failed_at, created_at, updated_at
FROM verifications
WHERE id = $1
  AND team_id = $2
FOR UPDATE
`

type GetVerificationForUpdateParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetVerificationForUpdate(ctx context.Context, arg GetVerificationForUpdateParams) (Verification, error) {
	row := q.db.QueryRow(ctx, getVerificationForUpdate, arg.ID, arg.TeamID)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ServiceID,
		&i.Channel,
		&i.Recipient,
		&i.RecipientNormalized,
		&i.Status,
		&i.Locale,
		&i.Metadata,
		&i.AttemptCount,
		&i.ResendCount,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExpiredAt,
		&i.CanceledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementVerificationAttemptCount = `-- name: IncrementVerificationAttemptCount :one
UPDATE verifications
SET attempt_count = attempt_count + 1,
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status = 'pending'
RETURNING id, team_id, service_id, channel, recipient, recipient_normalized, status, locale, metadata, attempt_count, resend_count, expires_at, approved_at, expired_at, canceled_at, failed_at, created_at, updated_at
`

type IncrementVerificationAttemptCountParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) IncrementVerificationAttemptCount(ctx context.Context, arg IncrementVerificationAttemptCountParams) (Verification, error) {
	row := q.db.QueryRow(ctx, incrementVerificationAttemptCount, arg.ID, arg.TeamID)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ServiceID,
		&i.Channel,
		&i.Recipient,
		&i.RecipientNormalized,
		&i.Status,
		&i.Locale,
		&i.Metadata,
		&i.AttemptCount,
		&i.ResendCount,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExpiredAt,
		&i.CanceledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementVerificationResendCount = `-- name: IncrementVerificationResendCount :one
UPDATE verifications
SET resend_count = resend_count + 1,
    expires_at = $1,
    updated_at = now()
WHERE id = $2
  AND team_id = $3
  AND status = 'pending'
RETURNING id, team_id, service_id, channel, recipient, recipient_normalized, status, locale, metadata, attempt_count, resend_count, expires_at, approved_at, expired_at, canceled_at, failed_at, created_at, updated_at
`

type IncrementVerificationResendCountParams struct {
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ID        uuid.UUID          `db:"id" json:"id"`
	TeamID    uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) IncrementVerificationResendCount(ctx context.Context, arg IncrementVerificationResendCountParams) (Verification, error) {
	row := q.db.QueryRow(ctx, incrementVerificationResendCount, arg.ExpiresAt, arg.ID, arg.TeamID)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ServiceID,
		&i.Channel,
		&i.Recipient,
		&i.RecipientNormalized,
		&i.Status,
		&i.Locale,
		&i.Metadata,
		&i.AttemptCount,
		&i.ResendCount,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExpiredAt,
		&i.CanceledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVerifications = `-- name: ListVerifications :many
SELECT verification.id, verification.team_id, verification.service_id, verification.channel, verification.recipient, verification.recipient_normalized, verification.status, verification.locale, verification.metadata, verification.attempt_count, verification.resend_count, verification.expires_at, verification.approved_at, verification.expired_at, verification.canceled_at, verification.failed_at, verification.created_at, verification.updated_at
FROM verifications AS verification
JOIN teams AS team ON team.id = verification.team_id
WHERE verification.team_id = $1
  AND team.status = 'active'
ORDER BY verification.created_at DESC, verification.id DESC
LIMIT $3
OFFSET $2
`

type ListVerificationsParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListVerifications(ctx context.Context, arg ListVerificationsParams) ([]Verification, error) {
	rows, err := q.db.Query(ctx, listVerifications, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Verification{}
	for rows.Next() {
		var i Verification
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ServiceID,
			&i.Channel,
			&i.Recipient,
			&i.RecipientNormalized,
			&i.Status,
			&i.Locale,
			&i.Metadata,
			&i.AttemptCount,
			&i.ResendCount,
			&i.ExpiresAt,
			&i.ApprovedAt,
			&i.ExpiredAt,
			&i.CanceledAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVerificationDeliveryFailed = `-- name: MarkVerificationDeliveryFailed :one
UPDATE verifications
SET status = 'delivery_failed',
    failed_at = now(),
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status = 'pending'
RETURNING id, team_id, service_id, channel, recipient, recipient_normalized, status, locale, metadata, attempt_count, resend_count, expires_at, approved_at, expired_at, canceled_at, failed_at, created_at, updated_at
`

type MarkVerificationDeliveryFailedParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkVerificationDeliveryFailed(ctx context.Context, arg MarkVerificationDeliveryFailedParams) (Verification, error) {
	row := q.db.QueryRow(ctx, markVerificationDeliveryFailed, arg.ID, arg.TeamID)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ServiceID,
		&i.Channel,
		&i.Recipient,
		&i.RecipientNormalized,
		&i.Status,
		&i.Locale,
		&i.Metadata,
		&i.AttemptCount,
		&i.ResendCount,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExpiredAt,
		&i.CanceledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markVerificationMaxAttemptsReached = `-- name: MarkVerificationMaxAttemptsReached :one
UPDATE verifications
SET status = 'max_attempts_reached',
    failed_at = now(),
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status = 'pending'
RETURNING id, team_id, service_id, channel, recipient, recipient_normalized, status, locale, metadata, attempt_count, resend_count, expires_at, approved_at, expired_at, canceled_at, failed_at, created_at, updated_at
`

type MarkVerificationMaxAttemptsReachedParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkVerificationMaxAttemptsReached(ctx context.Context, arg MarkVerificationMaxAttemptsReachedParams) (Verification, error) {
	row := q.db.QueryRow(ctx, markVerificationMaxAttemptsReached, arg.ID, arg.TeamID)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ServiceID,
		&i.Channel,
		&i.Recipient,
		&i.RecipientNormalized,
		&i.Status,
		&i.Locale,
		&i.Metadata,
		&i.AttemptCount,
		&i.ResendCount,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExpiredAt,
		&i.CanceledAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
