// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_attempts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createVerificationAttempt = `-- name: CreateVerificationAttempt :one
INSERT INTO verification_attempts (
    team_id, verification_id, challenge_id, result,
    ip_address_hash, user_agent, metadata
)
SELECT
    challenge.team_id,
    challenge.verification_id,
    challenge.id,
    $1,
    $2,
    $3,
    $4
FROM verification_challenges AS challenge
WHERE challenge.id = $5
  AND challenge.verification_id = $6
  AND challenge.team_id = $7
RETURNING id, team_id, verification_id, challenge_id, result, ip_address_hash, user_agent, metadata, attempted_at
`

type CreateVerificationAttemptParams struct {
	Result         string    `db:"result" json:"result"`
	IpAddressHash  []byte    `db:"ip_address_hash" json:"ip_address_hash"`
	UserAgent      *string   `db:"user_agent" json:"user_agent"`
	Metadata       []byte    `db:"metadata" json:"metadata"`
	ChallengeID    uuid.UUID `db:"challenge_id" json:"challenge_id"`
	VerificationID uuid.UUID `db:"verification_id" json:"verification_id"`
	TeamID         uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateVerificationAttempt(ctx context.Context, arg CreateVerificationAttemptParams) (VerificationAttempt, error) {
	row := q.db.QueryRow(ctx, createVerificationAttempt,
		arg.Result,
		arg.IpAddressHash,
		arg.UserAgent,
		arg.Metadata,
		arg.ChallengeID,
		arg.VerificationID,
		arg.TeamID,
	)
	var i VerificationAttempt
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.VerificationID,
		&i.ChallengeID,
		&i.Result,
		&i.IpAddressHash,
		&i.UserAgent,
		&i.Metadata,
		&i.AttemptedAt,
	)
	return i, err
}

const listVerificationAttempts = `-- name: ListVerificationAttempts :many
SELECT id, team_id, verification_id, challenge_id, result, ip_address_hash, user_agent, metadata, attempted_at
FROM verification_attempts
WHERE verification_id = $1
  AND team_id = $2
ORDER BY attempted_at DESC, id DESC
LIMIT $4
OFFSET $3
`

type ListVerificationAttemptsParams struct {
	VerificationID uuid.UUID `db:"verification_id" json:"verification_id"`
	TeamID         uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount    int32     `db:"offset_count" json:"offset_count"`
	LimitCount     int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListVerificationAttempts(ctx context.Context, arg ListVerificationAttemptsParams) ([]VerificationAttempt, error) {
	rows, err := q.db.Query(ctx, listVerificationAttempts,
		arg.VerificationID,
		arg.TeamID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerificationAttempt{}
	for rows.Next() {
		var i VerificationAttempt
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.VerificationID,
			&i.ChallengeID,
			&i.Result,
			&i.IpAddressHash,
			&i.UserAgent,
			&i.Metadata,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
