// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_challenges.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVerificationChallenge = `-- name: CreateVerificationChallenge :one
INSERT INTO verification_challenges (
    team_id, verification_id, sequence, code_hmac, status, channel, expires_at
)
SELECT
    verification.team_id, verification.id, $1, $2,
    'queued', $3, $4
FROM verifications AS verification
WHERE verification.id = $5
  AND verification.team_id = $6
  AND verification.status = 'pending'
RETURNING id, team_id, verification_id, sequence, code_hmac, status, channel, email_message_id, sms_message_id, expires_at, superseded_at, dispatched_at, delivery_failed_at, created_at, updated_at
`

type CreateVerificationChallengeParams struct {
	Sequence       int32              `db:"sequence" json:"sequence"`
	CodeHmac       []byte             `db:"code_hmac" json:"code_hmac"`
	Channel        string             `db:"channel" json:"channel"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	VerificationID uuid.UUID          `db:"verification_id" json:"verification_id"`
	TeamID         uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateVerificationChallenge(ctx context.Context, arg CreateVerificationChallengeParams) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, createVerificationChallenge,
		arg.Sequence,
		arg.CodeHmac,
		arg.Channel,
		arg.ExpiresAt,
		arg.VerificationID,
		arg.TeamID,
	)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.VerificationID,
		&i.Sequence,
		&i.CodeHmac,
		&i.Status,
		&i.Channel,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.ExpiresAt,
		&i.SupersededAt,
		&i.DispatchedAt,
		&i.DeliveryFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveVerificationChallengeForUpdate = `-- name: GetActiveVerificationChallengeForUpdate :one
SELECT id, team_id, verification_id, sequence, code_hmac, status, channel, email_message_id, sms_message_id, expires_at, superseded_at, dispatched_at, delivery_failed_at, created_at, updated_at
FROM verification_challenges
WHERE verification_id = $1
  AND team_id = $2
  AND status IN ('queued', 'dispatching', 'dispatched')
ORDER BY sequence DESC
LIMIT 1
FOR UPDATE
`

type GetActiveVerificationChallengeForUpdateParams struct {
	VerificationID uuid.UUID `db:"verification_id" json:"verification_id"`
	TeamID         uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetActiveVerificationChallengeForUpdate(ctx context.Context, arg GetActiveVerificationChallengeForUpdateParams) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, getActiveVerificationChallengeForUpdate, arg.VerificationID, arg.TeamID)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.VerificationID,
		&i.Sequence,
		&i.CodeHmac,
		&i.Status,
		&i.Channel,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.ExpiresAt,
		&i.SupersededAt,
		&i.DispatchedAt,
		&i.DeliveryFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerificationChallenge = `-- name: GetVerificationChallenge :one
SELECT id, team_id, verification_id, sequence, code_hmac, status, channel, email_message_id, sms_message_id, expires_at, superseded_at, dispatched_at, delivery_failed_at, created_at, updated_at
FROM verification_challenges
WHERE id = $1
  AND team_id = $2
`

type GetVerificationChallengeParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetVerificationChallenge(ctx context.Context, arg GetVerificationChallengeParams) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, getVerificationChallenge, arg.ID, arg.TeamID)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.VerificationID,
		&i.Sequence,
		&i.CodeHmac,
		&i.Status,
		&i.Channel,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.ExpiresAt,
		&i.SupersededAt,
		&i.DispatchedAt,
		&i.DeliveryFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVerificationChallenges = `-- name: ListVerificationChallenges :many
SELECT id, team_id, verification_id, sequence, code_hmac, status, channel, email_message_id, sms_message_id, expires_at, superseded_at, dispatched_at, delivery_failed_at, created_at, updated_at
FROM verification_challenges
WHERE verification_id = $1
  AND team_id = $2
ORDER BY sequence DESC
`

type ListVerificationChallengesParams struct {
	VerificationID uuid.UUID `db:"verification_id" json:"verification_id"`
	TeamID         uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ListVerificationChallenges(ctx context.Context, arg ListVerificationChallengesParams) ([]VerificationChallenge, error) {
	rows, err := q.db.Query(ctx, listVerificationChallenges, arg.VerificationID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerificationChallenge{}
	for rows.Next() {
		var i VerificationChallenge
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.VerificationID,
			&i.Sequence,
			&i.CodeHmac,
			&i.Status,
			&i.Channel,
			&i.EmailMessageID,
			&i.SmsMessageID,
			&i.ExpiresAt,
			&i.SupersededAt,
			&i.DispatchedAt,
			&i.DeliveryFailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVerificationChallengeDeliveryFailed = `-- name: MarkVerificationChallengeDeliveryFailed :one
UPDATE verification_challenges
SET status = 'delivery_failed',
    delivery_failed_at = now(),
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status IN ('queued', 'dispatching')
RETURNING id, team_id, verification_id, sequence, code_hmac, status, channel, email_message_id, sms_message_id, expires_at, superseded_at, dispatched_at, delivery_failed_at, created_at, updated_at
`

type MarkVerificationChallengeDeliveryFailedParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkVerificationChallengeDeliveryFailed(ctx context.Context, arg MarkVerificationChallengeDeliveryFailedParams) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, markVerificationChallengeDeliveryFailed, arg.ID, arg.TeamID)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.VerificationID,
		&i.Sequence,
		&i.CodeHmac,
		&i.Status,
		&i.Channel,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.ExpiresAt,
		&i.SupersededAt,
		&i.DispatchedAt,
		&i.DeliveryFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markVerificationChallengeDispatching = `-- name: MarkVerificationChallengeDispatching :one
UPDATE verification_challenges
SET status = 'dispatching',
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status = 'queued'
RETURNING id, team_id, verification_id, sequence, code_hmac, status, channel, email_message_id, sms_message_id, expires_at, superseded_at, dispatched_at, delivery_failed_at, created_at, updated_at
`

type MarkVerificationChallengeDispatchingParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkVerificationChallengeDispatching(ctx context.Context, arg MarkVerificationChallengeDispatchingParams) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, markVerificationChallengeDispatching, arg.ID, arg.TeamID)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.VerificationID,
		&i.Sequence,
		&i.CodeHmac,
		&i.Status,
		&i.Channel,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.ExpiresAt,
		&i.SupersededAt,
		&i.DispatchedAt,
		&i.DeliveryFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markVerificationChallengeEmailDispatched = `-- name: MarkVerificationChallengeEmailDispatched :one
UPDATE verification_challenges
SET status = 'dispatched',
    email_message_id = $1,
    dispatched_at = now(),
    updated_at = now()
WHERE id = $2
  AND team_id = $3
  AND channel = 'email'
  AND status IN ('queued', 'dispatching')
RETURNING id, team_id, verification_id, sequence, code_hmac, status, channel, email_message_id, sms_message_id, expires_at, superseded_at, dispatched_at, delivery_failed_at, created_at, updated_at
`

type MarkVerificationChallengeEmailDispatchedParams struct {
	EmailMessageID *uuid.UUID `db:"email_message_id" json:"email_message_id"`
	ID             uuid.UUID  `db:"id" json:"id"`
	TeamID         uuid.UUID  `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkVerificationChallengeEmailDispatched(ctx context.Context, arg MarkVerificationChallengeEmailDispatchedParams) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, markVerificationChallengeEmailDispatched, arg.EmailMessageID, arg.ID, arg.TeamID)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.VerificationID,
		&i.Sequence,
		&i.CodeHmac,
		&i.Status,
		&i.Channel,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.ExpiresAt,
		&i.SupersededAt,
		&i.DispatchedAt,
		&i.DeliveryFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markVerificationChallengeExpired = `-- name: MarkVerificationChallengeExpired :one
UPDATE verification_challenges
SET status = 'expired',
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status IN ('queued', 'dispatching', 'dispatched')
RETURNING id, team_id, verification_id, sequence, code_hmac, status, channel, email_message_id, sms_message_id, expires_at, superseded_at, dispatched_at, delivery_failed_at, created_at, updated_at
`

type MarkVerificationChallengeExpiredParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkVerificationChallengeExpired(ctx context.Context, arg MarkVerificationChallengeExpiredParams) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, markVerificationChallengeExpired, arg.ID, arg.TeamID)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.VerificationID,
		&i.Sequence,
		&i.CodeHmac,
		&i.Status,
		&i.Channel,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.ExpiresAt,
		&i.SupersededAt,
		&i.DispatchedAt,
		&i.DeliveryFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markVerificationChallengeSMSDispatched = `-- name: MarkVerificationChallengeSMSDispatched :one
UPDATE verification_challenges
SET status = 'dispatched',
    sms_message_id = $1,
    dispatched_at = now(),
    updated_at = now()
WHERE id = $2
  AND team_id = $3
  AND channel = 'sms'
  AND status IN ('queued', 'dispatching')
RETURNING id, team_id, verification_id, sequence, code_hmac, status, channel, email_message_id, sms_message_id, expires_at, superseded_at, dispatched_at, delivery_failed_at, created_at, updated_at
`

type MarkVerificationChallengeSMSDispatchedParams struct {
	SmsMessageID *uuid.UUID `db:"sms_message_id" json:"sms_message_id"`
	ID           uuid.UUID  `db:"id" json:"id"`
	TeamID       uuid.UUID  `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkVerificationChallengeSMSDispatched(ctx context.Context, arg MarkVerificationChallengeSMSDispatchedParams) (VerificationChallenge, error) {
	row := q.db.QueryRow(ctx, markVerificationChallengeSMSDispatched, arg.SmsMessageID, arg.ID, arg.TeamID)
	var i VerificationChallenge
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.VerificationID,
		&i.Sequence,
		&i.CodeHmac,
		&i.Status,
		&i.Channel,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.ExpiresAt,
		&i.SupersededAt,
		&i.DispatchedAt,
		&i.DeliveryFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const supersedeActiveVerificationChallenges = `-- name: SupersedeActiveVerificationChallenges :many
UPDATE verification_challenges
SET status = 'superseded',
    superseded_at = now(),
    updated_at = now()
WHERE verification_id = $1
  AND team_id = $2
  AND status IN ('queued', 'dispatching', 'dispatched')
RETURNING id, team_id, verification_id, sequence, code_hmac, status, channel, email_message_id, sms_message_id, expires_at, superseded_at, dispatched_at, delivery_failed_at, created_at, updated_at
`

type SupersedeActiveVerificationChallengesParams struct {
	VerificationID uuid.UUID `db:"verification_id" json:"verification_id"`
	TeamID         uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) SupersedeActiveVerificationChallenges(ctx context.Context, arg SupersedeActiveVerificationChallengesParams) ([]VerificationChallenge, error) {
	rows, err := q.db.Query(ctx, supersedeActiveVerificationChallenges, arg.VerificationID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerificationChallenge{}
	for rows.Next() {
		var i VerificationChallenge
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.VerificationID,
			&i.Sequence,
			&i.CodeHmac,
			&i.Status,
			&i.Channel,
			&i.EmailMessageID,
			&i.SmsMessageID,
			&i.ExpiresAt,
			&i.SupersededAt,
			&i.DispatchedAt,
			&i.DeliveryFailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
